<h1>TODO</h1>
<ol>
</ol>

1. Clean up the code

In [1]:
import sys
stdout = sys.stdout
sys.stdout = stdout

In [2]:
import nupack
from nupack import *
from collections import deque
import pandas as pd
import gspread
import RNA
from copy import copy, deepcopy
#Change below from 20 to 'None' if you want to see full display
pd.set_option('display.max_rows', 20)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
from Bio.Seq import Seq
import numpy as np
import yaml

In [3]:
def export_sheet (link):
    f_part = link.split('/edit#gid')[0]
    return f_part + '/export?format=csv'

In [4]:
model1 = Model()
#Model parameters go here

salt_concentrations_list = [0,0.01,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1]
#salt_concentrations_list = [0, 0.01]
csv_names = ['(0.0) Molarity-Coxsackievirus-Data.csv',
             '(0.01) Molarity-Coxsackievirus-Data.csv',
             '(0.1) Molarity-Coxsackievirus-Data.csv',
             '(0.2) Molarity-Coxsackievirus-Data.csv',
             '(0.3) Molarity-Coxsackievirus-Data.csv',
             '(0.4) Molarity-Coxsackievirus-Data.csv',
             '(0.5) Molarity-Coxsackievirus-Data.csv',
             '(0.6) Molarity-Coxsackievirus-Data.csv',
             '(0.7) Molarity-Coxsackievirus-Data.csv',
             '(0.8) Molarity-Coxsackievirus-Data.csv',
             '(0.9) Molarity-Coxsackievirus-Data.csv',
             '(1.0) Molarity-Coxsackievirus-Data.csv']

cherry_csv_names = ['(0.0) Molarity-Cherry-Cox-Data.csv',
             '(0.01) Molarity-Cherry-Cox-Data.csv',
             '(0.1) Molarity-Cherry-Cox-Data.csv',
             '(0.2) Molarity-Cherry-Cox-Data.csv',
             '(0.3) Molarity-Cherry-Cox-Data.csv',
             '(0.4) Molarity-Cherry-Cox-Data.csv',
             '(0.5) Molarity-Cherry-Cox-Data.csv',
             '(0.6) Molarity-Cherry-Cox-Data.csv',
             '(0.7) Molarity-Cherry-Cox-Data.csv',
             '(0.8) Molarity-Cherry-Cox-Data.csv',
             '(0.9) Molarity-Cherry-Cox-Data.csv',
             '(1.0) Molarity-Cherry-Cox-Data.csv']

lacZ_csv_names = ['(0.0) Molarity-LacZ-Cox-Data.csv',
             '(0.01) Molarity-LacZ-Cox-Data.csv',
             '(0.1) Molarity-LacZ-Cox-Data.csv',
             '(0.2) Molarity-LacZ-Cox-Data.csv',
             '(0.3) Molarity-LacZ-Cox-Data.csv',
             '(0.4) Molarity-LacZ-Cox-Data.csv',
             '(0.5) Molarity-LacZ-Cox-Data.csv',
             '(0.6) Molarity-LacZ-Cox-Data.csv',
             '(0.7) Molarity-LacZ-Cox-Data.csv',
             '(0.8) Molarity-LacZ-Cox-Data.csv',
             '(0.9) Molarity-LacZ-Cox-Data.csv',
             '(1.0) Molarity-LacZ-Cox-Data.csv']

lacZ_seq = 'AACTTAATCGCCTTGCAGCACATCCCCCTTTCGCCAGCTGGCGTAATAGCGAAGAGGCCCGCACCGATCGCCCTTCCCAACAGTTGCGCAGCCTGAATGGCGAATGGCGCTTTGCCTGGTTTCCGGCACCAGAAGCGGTGCCGGAAAGCTGGCTGGAGTGCGATCTTCCTGAGGCCGATACTGTCGTCGTCCCCTCAAACTGGCAGATGCACGGTTACGATGCGCCCATCTACACCAACGTGACCTATCCCATTACGGTCAATCCGCCGTTTGTTCCCACGGAGAATCCGACGGGTTGTTACTCGCTCACATTTAATGTTGATGAAAGCTGGCTACAGGAAGGCCAGACGCGAATTATTTTTGATGGCGTTAACTCGGCGTTTCATCTGTGGTGCAACGGGCGCTGGGTCGGTTACGGCCAGGACAGTCGTTTGCCGTCTGAATTTGACCTGAGCGCATTTTTACGCGCCGGAGAAAACCGCCTCGCGGTGATGGTGCTGCGCTGGAGTGACGGCAGTTATCTGGAAGATCAGGATATGTGGCGGATGAGCGGCATTTTCCGTGACGTCTCGTTGCTGCATAAACCGACTACACAAATCAGCGATTTCCATGTTGCCACTCGCTTTAATGATGATTTCAGCCGCGCTGTACTGGAGGCTGAAGTTCAGATGTGCGGCGAGTTGCGTGACTACCTACGGGTAACAGTTTCTTTATGGCAGGGTGAAACGCAGGTCGCCAGCGGCACCGCGCCTTTCGGCGGTGAAATTATCGATGAGCGTGGTGGTTATGCCGATCGCGTCACACTACGTCTGAACGTCGAAAACCCGAAACTGTGGAGCGCCGAAATCCCGAATCTCTATCGTGCGGTGGTTGAACTGCACACCGCCGACGGCACGCTGATTGAAGCAGAAGCCTGCGATGTCGGTTTCCGCGAGGTGCGGATTGAAAATGGTCTGCTGCTGCTGAACGGCAAGCCGTTGCTGATTCGAGGCGTTAACCGTCACGAGCATCATCCTCTGCATGGTCAGGTCATGGATGAGCAGACGATGGTGCAGGATATCCTGCTGATGAAGCAGAACAACTTTAACGCCGTGCGCTGTTCGCATTATCCGAACCATCCGCTGTGGTACACGCTGTGCGACCGCTACGGCCTGTATGTGGTGGATGAAGCCAATATTGAAACCCACGGCATGGTGCCAATGAATCGTCTGACCGATGATCCGCGCTGGCTACCGGCGATGAGCGAACGCGTAACGCGAATGGTGCAGCGCGATCGTAATCACCCGAGTGTGATCATCTGGTCGCTGGGGAATGAATCAGGCCACGGCGCTAATCACGACGCGCTGTATCGCTGGATCAAATCTGTCGATCCTTCCCGCCCGGTGCAGTATGAAGGCGGCGGAGCCGACACCACGGCCACCGATATTATTTGCCCGATGTACGCGCGCGTGGATGAAGACCAGCCCTTCCCGGCTGTGCCGAAATGGTCCATCAAAAAATGGCTTTCGCTACCTGGAGAGACGCGCCCGCTGATCCTTTGCGAATACGCCCACGCGATGGGTAACAGTCTTGGCGGTTTCGCTAAATACTGGCAGGCGTTTCGTCAGTATCCCCGTTTACAGGGCGGCTTCGTCTGGGACTGGGTGGATCAGTCGCTGATTAAATATGATGAAAACGGCAACCCGTGGTCGGCTTACGGCGGTGATTTTGGCGATACGCCGAACGATCGCCAGTTCTGTATGAACGGTCTGGTCTTTGCCGACCGCACGCCGCATCCAGCGCTGACGGAAGCAAAACACCAGCAGCAGTTTTTCCAGTTCCGTTTATCCGGGCAAACCATCGAAGTGACCAGCGAATACCTGTTCCGTCATAGCGATAACGAGCTCCTGCACTGGATGGTGGCGCTGGATGGTAAGCCGCTGGCAAGCGGTGAAGTGCCTCTGGATGTCGCTCCACAAGGTAAACAGTTGATTGAACTGCCTGAACTACCGCAGCCGGAGAGCGCCGGGCAACTCTGGCTCACAGTACGCGTAGTGCAACCGAACGCGACCGCATGGTCAGAAGCCGGGCACATCAGCGCCTGGCAGCAGTGGCGTCTGGCGGAAAACCTCAGTGTGACGCTCCCCGCCGCGTCCCACGCCATCCCGCATCTGACCACCAGCGAAATGGATTTTTGCATCGAGCTGGGTAATAAGCGTTGGCAATTTAACCGCCAGTCAGGCTTTCTTTCACAGATGTGGATTGGCGATAAAAAACAACTGCTGACGCCGCTGCGCGATCAGTTCACCCGTGCACCGCTGGATAACGACATTGGCGTAAGTGAAGCGACCCGCATTGACCCTAACGCCTGGGTCGAACGCTGGAAGGCGGCGGGCCATTACCAGGCCGAAGCAGCGTTGTTGCAGTGCACGGCAGATACACTTGCTGATGCGGTGCTGATTACGACCGCTCACGCGTGGCAGCATCAGGGGAAAACCTTATTTATCAGCCGGAAAACCTACCGGATTGATGGTAGTGGTCAAATGGCGATTACCGTTGATGTTGAAGTGGCGAGCGATACACCGCATCCGGCGCGGATTGGCCTGAACTGCCAGCTGGCGCAGGTAGCAGAGCGGGTAAACTGGCTCGGATTAGGGCCGCAAGAAAACTATCCCGACCGCCTTACTGCCGCCTGTTTTGACCGCTGGGATCTGCCATTGTCAGACATGTATACCCCGTACGTCTTCCCGAGCGAAAACGGTCTGCGCTGCGGGACGCGCGAATTGAATTATGGCCCACACCAGTGGCGCGGCGACTTCCAGTTCAACATCAGCCGCTACAGTCAACAGCAACTGATGGAAACCAGCCATCGCCATCTGCTGCACGCGGAAGAAGGCACATGGCTGAATATCGACGGTTTCCATATGGGGATTGGTGGCGACGACTCCTGGAGCCCGTCAGTATCGGCGGAATTCCAGCTGAGCGCCGGTCGCTACCATTACCAGTTGGTCTGGTGTCAAAAATAA'
cherry_seq = 'ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGTTCATGCGCTTCAAGGTTCACATGGAGGGCTCCGTGAACGGCCACGAGTTCGAGATCGAGGGCGAGGGCGAGGGCCGCCCCTACGAGGGCACCCAGACCGCCAAGCTGAAGGTGACCAAGGGTGGCCCCCTGCCCTTCGCCTGGGACATCCTGTCCCCTCAGTTCATGTACGGCTCCAAGGCCTACGTGAAGCACCCCGCCGACATCCCCGACTACTTGAAGCTGTCCTTCCCCGAGGGCTTCAAGTGGGAGCGCGTGATGAACTTCGAGGACGGCGGCGTGGTGACCGTGACCCAGGACTCCTCCCTGCAAGACGGCGAGTTCATCTACAAGGTGAAGCTGCGCGGCACCAACTTCCCCTCCGACGGCCCCGTAATGCAGAAGAAGACTATGGGCTGGGAGGCCTCCTCCGAGCGGATGTACCCCGAGGACGGCGCGCTGAAGGGCGAGATCAAGCAGAGGCTGAAGCTGAAGGACGGCGGCCACTACGACGCTGAGGTCAAGACCACCTACAAGGCCAAGAAGCCCGTGCAACTGCCCGGCGCGTACAACGTCAACATCAAGTTGGACATCACCTCCCACAACGAGGACTACACCATCGTGGAACAGTACGAACGCGCCGAGGGCCGCCACTCCACCGGCGGCATGGACGAGCTGTACAAGTAA'
temp = 25.0
#lacZ_seq = lacZ_seq[:10]
#cherry_seq = cherry_seq[:10]
md = RNA.md()
md.temperature = temp   
#md.sfact = .80

#md_parameters = len(salt_molarity)
#end of parameters

sheet_link = 'https://docs.google.com/spreadsheets/d/1idf3GHur5Eneef_vnwpGD-dn_dhoEgqx/edit#gid=1170226371'
sheet_rows = 34 #how many rows we want to use
f_part = sheet_link.split('/edit#gid')[0]
csv_link = f_part + '/export?format=csv'
data = pd.read_csv(csv_link)
df = pd.read_csv(csv_link, usecols=['toehold_switch_sequence','target_sequence', 'location'], nrows=sheet_rows)
# df.insert(len(df.columns), 'switch_energy', 1.0)
# df.insert(len(df.columns), 'target_energy', 1.0)
# df.insert(len(df.columns), 'switch_gc_count', -1)
# df.insert(len(df.columns), 'target_gc_count',-1)
# df.insert(len(df.columns), 'ensemble_defect_switch', 0)
# df.insert(len(df.columns), 'ensemble_defect_target', 0)
df.columns = df.columns.str.replace('location', 'target_location')

preliminary_data_names = ['switch_structure', 'target_structure', 'switch_energy', 'target_energy', 'switch_gc', 'switch_at' 'target_gc', 'target_at', 'switch_ensemble_defect', 'target_ensemble_defect', 'switch_single_strandedness', 'target_single_strandedness']
old_data_names = ['salt_molarity', 'temperature (Celsius)', 'switch_row', 'target_row', 'target_location', 'toehold_switch_sequence', 'target_sequence', 'switch_mfe_structure', 'target_mfe_structure', 'switch_energy','switch_gc', 'switch_ensemble_defect', 'switch_single_strandedness', 'target_energy', 'target_gc', 'target_ensemble_defect', 'target_single_strandedness', 'valid_loop', 'loop_sequence', 'loop_structure', 'loop_energy', 'complex_nucelotides', 'complex_structure', 'complex_visualization_structure', 'complex_energy', 'complex_gc', 'complex_ensemble_defect', 'complex_single_strandedness']
finished_data_names = ['salt_molarity', 'temperature (Celsius)', 'switch_row', 'target_row', 'target_location', 'toehold_switch_sequence', 'target_sequence', 'reporter_sequence', 'complex_nucelotides', 'switch_structure', 'target_structure', 'reporter_structure', 'complex_structure', 'complex_visualization_structure', 'switch_energy', 'target_energy', 'reporter_energy', 'complex_energy', 'switch_gc', 'target_gc', 'reporter_gc', 'reporter_at', 'complex_gc', 'switch_ensemble_defect', 'target_ensemble_defect', 'reporter_ensemble_defect', 'complex_ensemble_defect', 'switch_single_strandedness', 'target_single_strandedness', 'reporter_single_strandedness', 'complex_single_strandedness', 'valid_loop', 'loop_sequence', 'loop_structure', 'loop_energy']

In [5]:
ms2_data = pd.read_csv('MS2 bacteriophage - Sheet1.csv',usecols=['RNA polymerase Sequence (30bp)', 'Location'])

In [6]:
full_target_data = pd.read_csv("sequence_output.csv")
display(full_target_data)

     Location                        Sequence
0        1879  TGAGGTTGACTCAGTTGTCCCAGTCCAAAA
1        1880  GAGGTTGACTCAGTTGTCCCAGTCCAAAAT
2        1881  AGGTTGACTCAGTTGTCCCAGTCCAAAATG
3        1882  GGTTGACTCAGTTGTCCCAGTCCAAAATGT
4        1883  GTTGACTCAGTTGTCCCAGTCCAAAATGTT
..        ...                             ...
147      2026  TCGGACGCTCCTAGGAGAGATCTTGAACTA
148      2027  CGGACGCTCCTAGGAGAGATCTTGAACTAT
149      2028  GGACGCTCCTAGGAGAGATCTTGAACTATT
150      2029  GACGCTCCTAGGAGAGATCTTGAACTATTA
151      2030  ACGCTCCTAGGAGAGATCTTGAACTATTAT

[152 rows x 2 columns]

In [7]:
green_cherry_csv_names = ['(0.0) Green-Cherry-Cox-Data.csv',
             '(0.01) Green-Cherry-Cox-Data.csv',
             '(0.1) Green-Cherry-Cox-Data.csv',
             '(0.2) Green-Cherry-Cox-Data.csv',
             '(0.3) Green-Cherry-Cox-Data.csv',
             '(0.4) Green-Cherry-Cox-Data.csv',
             '(0.5) Green-Cherry-Cox-Data.csv',
             '(0.6) Green-Cherry-Cox-Data.csv',
             '(0.7) Green-Cherry-Cox-Data.csv',
             '(0.8) Green-Cherry-Cox-Data.csv',
             '(0.9) Green-Cherry-Cox-Data.csv',
             '(1.0) Green-Cherry-Cox-Data.csv']

green_lacZ_csv_names = ['(0.0) Green-LacZ-Cox-Data.csv',
             '(0.01) Green-LacZ-Cox-Data.csv',
             '(0.1) Green-LacZ-Cox-Data.csv',
             '(0.2) Green-LacZ-Cox-Data.csv',
             '(0.3) Green-LacZ-Cox-Data.csv',
             '(0.4) Green-LacZ-Cox-Data.csv',
             '(0.5) Green-LacZ-Cox-Data.csv',
             '(0.6) Green-LacZ-Cox-Data.csv',
             '(0.7) Green-LacZ-Cox-Data.csv',
             '(0.8) Green-LacZ-Cox-Data.csv',
             '(0.9) Green-LacZ-Cox-Data.csv',
             '(1.0) Green-LacZ-Cox-Data.csv']

In [37]:
ms2_cherry_csv_names = ['(0.0) Molarity-MS2-Cherry-Data.csv',
             '(0.01) Molarity-MS2-Cherry-Data.csv',
             '(0.1) Molarity-MS2-Cherry-Data.csv',
             '(0.2) Molarity-MS2-Cherry-Data.csv',
             '(0.3) Molarity-MS2-Cherry-Data.csv',
             '(0.4) Molarity-MS2-Cherry-Data.csv',
             '(0.5) Molarity-MS2-Cherry-Data.csv',
             '(0.6) Molarity-MS2-Cherry-Data.csv',
             '(0.7) Molarity-MS2-Cherry-Data.csv',
             '(0.8) Molarity-MS2-Cherry-Data.csv',
             '(0.9) Molarity-MS2-Cherry-Data.csv',
             '(1.0) Molarity-MS2-Cherry-Data.csv']

ms2_green_cherry_csv_names = ['(0.0) Green-MS2-Cherry-Data.csv',
             '(0.01) Green-MS2-Cherry-Data.csv',
             '(0.1) Green-MS2-Cherry-Data.csv',
             '(0.2) Green-MS2-Cherry-Data.csv',
             '(0.3) Green-MS2-Cherry-Data.csv',
             '(0.4) Green-MS2-Cherry-Data.csv',
             '(0.5) Green-MS2-Cherry-Data.csv',
             '(0.6) Green-MS2-Cherry-Data.csv',
             '(0.7) Green-MS2-Cherry-Data.csv',
             '(0.8) Green-MS2-Cherry-Data.csv',
             '(0.9) Green-MS2-Cherry-Data.csv',
             '(1.0) Green-MS2-Cherry-Data.csv']

ms2_lacZ_csv_names = ['(0.0) Molarity-MS2-LacZ-Data.csv',
             '(0.01) Molarity-MS2-LacZ-Data.csv',
             '(0.1) Molarity-MS2-LacZ-Data.csv',
             '(0.2) Molarity-MS2-LacZ-Data.csv',
             '(0.3) Molarity-MS2-LacZ-Data.csv',
             '(0.4) Molarity-MS2-LacZ-Data.csv',
             '(0.5) Molarity-MS2-LacZ-Data.csv',
             '(0.6) Molarity-MS2-LacZ-Data.csv',
             '(0.7) Molarity-MS2-LacZ-Data.csv',
             '(0.8) Molarity-MS2-LacZ-Data.csv',
             '(0.9) Molarity-MS2-LacZ-Data.csv',
             '(1.0) Molarity-MS2-LacZ-Data.csv']

# ms2_green_lacZ_csv_names = ['(0.0) Green-MS2-LacZ-Data.csv',
#              '(0.01) Green-MS2-LacZ-Data.csv',
#              '(0.1) Green-MS2-LacZ-Data.csv',
#              '(0.2) Green-MS2-LacZ-Data.csv',
#              '(0.3) Green-MS2-LacZ-Data.csv',
#              '(0.4) Green-MS2-LacZ-Data.csv',
#              '(0.5) Green-MS2-LacZ-Data.csv',
#              '(0.6) Green-MS2-LacZ-Data.csv',
#              '(0.7) Green-MS2-LacZ-Data.csv',
#              '(0.8) Green-MS2-LacZ-Data.csv',
#              '(0.9) Green-MS2-LacZ-Data.csv',
#              '(1.0) Green-MS2-LacZ-Data.csv']

ms2_green_lacZ_csv_names = ['(0.1) Green-MS2-LacZ-Data.csv',
             '(1.0) Green-MS2-LacZ-Data.csv']

In [9]:
target_col_name = ''
switch_col_name = ''

In [10]:
riboswitch_table_names = ['name_of_riboswitch_data', 'riboswitch_subcategory', 'switch_row','riboswitch_sequence','switch_structure', 
                          'switch_energy', 'switch_gc', 'switch_at', 'switch_ensemble_defect', 
                          'switch_single_strandedness', 'trigger_single_strandedness', 'trigger_structure', 'switch_kmers',
                          'rbs_validity', 'rbs_location']
target_table_names = ['name_of_target_data','target_location', 'target_sequence','target_structure', 'target_energy','target_gc','target_at',
                      'target_ensemble_defect', 'target_single_strandedness', 'target_kmers']

In [11]:
preliminary_data_names = ['switch_structure', 'target_structure', 'switch_energy', 'target_energy', 'switch_gc', 'switch_at', 'target_gc', 'target_at', 'switch_ensemble_defect', 'target_ensemble_defect', 'switch_single_strandedness', 'target_single_strandedness']

old_data_names = ['salt_molarity', 'temperature (Celsius)', 'switch_row', 'target_row', 'target_location', 'toehold_switch_sequence', 'target_sequence', 'switch_mfe_structure', 'target_mfe_structure', 'switch_energy','switch_gc', 'switch_ensemble_defect', 'switch_single_strandedness', 'target_energy', 'target_gc', 'target_ensemble_defect', 'target_single_strandedness', 'valid_loop', 'loop_sequence', 'loop_structure', 'loop_energy', 'complex_nucelotides', 'complex_structure', 'complex_visualization_structure', 'complex_energy', 'complex_gc', 'complex_ensemble_defect', 'complex_single_strandedness']
old_finished_data_names = ['salt_molarity', 'temperature (Celsius)', 'switch_row', 'target_row', 'target_location', 'toehold_switch_sequence', 'target_sequence', 'reporter_sequence', 'complex_nucelotides', 'switch_structure', 'target_structure', 'reporter_structure', 'complex_structure', 'complex_visualization_structure', 'switch_energy', 'target_energy', 'reporter_energy', 'complex_energy', 'switch_gc', 'switch_at', 'target_gc', 'target_at', 'reporter_gc', 'reporter_at', 'complex_gc', 'complex_at', 'switch_ensemble_defect', 'target_ensemble_defect', 'reporter_ensemble_defect', 'complex_ensemble_defect', 'switch_single_strandedness', 'target_single_strandedness', 'reporter_single_strandedness', 'complex_single_strandedness', 'valid_loop', 'loop_sequence', 'loop_structure', 'loop_energy']
finished_data_names = ['label','salt_molarity', 'temperature (Celsius)', 'name_of_riboswitch_data','name_of_target_data','riboswitch_subcategory',
                       'switch_row', 'target_row', 'trigger_row','target_location', 'trigger_location',
                       'riboswitch_sequence', 'target_sequence', 'trigger_sequence', 'target_trigger_complex','reporter_sequence', 'complex_nucelotides', 
                       'switch_structure', 'target_structure', 'reporter_structure', 'complex_structure', 'trigger_target_binding_percentage',
                       'switch_energy', 'target_energy', 'reporter_energy', 'complex_energy', 
                       'switch_gc', 'switch_at', 'target_gc', 'target_at', 'reporter_gc', 'reporter_at', 'complex_gc', 'complex_at', 
                       'switch_ensemble_defect', 'target_ensemble_defect', 'reporter_ensemble_defect', 'complex_ensemble_defect', 
                       'switch_single_strandedness', 'target_single_strandedness', 'reporter_single_strandedness', 'complex_single_strandedness', 
                       'trigger_single_strandedness', 'trigger_structure', 
                       'switch_kmers','target_kmers','complex_kmers',
                       'rbs_validity','rbs_location',
                       'valid_loop','loop_sequence', 'loop_structure', 'loop_energy']

In [12]:
def transcribe_dna_to_rna(seq):
    return seq.translate(str.maketrans("tT", "uU"))

In [13]:
def reverse_complement_sequencer(target):
    seq = Seq(target)
    return transcribe_dna_to_rna(str(seq.reverse_complement()).upper())

In [14]:
def trigger_generator(t_df, target_col, location_col = -1):
    target_df = t_df
    trigger_df = pd.DataFrame()
    trigger_df['trigger_sequence'] = target_df.iloc[:, target_col].apply(reverse_complement_sequencer).to_frame()
    trigger_df['Location'] = pd.Series()
    trigger_df = trigger_df[['Location','trigger_sequence']]
    if location_col>-1:
        trigger_df['Location'] = target_df.iloc[:, [location_col]]
    # display(target_df)
    # display(trigger_df)
    return trigger_df

In [15]:
#computes ammounts of gc in sequence
def oneComputeGCtotal(seq):
    gc_content = 0
    total_bases = len(seq)
    idx = 0
    while idx < len(seq):
        seq_idx = seq[idx]
        if seq_idx == 'C' or seq_idx == 'G':
            gc_content += 1
        idx += 1
    gc_cont_perc = float(gc_content) / float(total_bases)
    return gc_cont_perc

In [16]:
def compute_AT_and_GC_percent(seq):
    gc_percent = oneComputeGCtotal(seq)
    at_percent = float(1) - gc_percent
    return [gc_percent,at_percent]

In [17]:
#For an entire base probability matrix, can't specify start or end
def find_single_strandedness(base_pair_probability_matrix): #This was taken from Andrew's code, for some reason it's not working as intended... possible that diagonals means something different in Vienna
    assert base_pair_probability_matrix.ndim == 2, "matrix must be two dimensional"
    assert base_pair_probability_matrix.shape[0] == base_pair_probability_matrix.shape[1], "matrix must be square"

    # sum_of_diagonal = np.sum(np.diag(base_pair_probability_matrix))
    # length_of_sequence = base_pair_probability_matrix.shape[0]
    # return sum_of_diagonal/length_of_sequence
    top_triangle_probability_matrix = np.triu(base_pair_probability_matrix, 1)#zeroes out the main diagonal of the matrix plus all the diagonals below it
    probability_for_each_nucleotide = np.sum(top_triangle_probability_matrix, axis=0)#Give us the probability of each nucleotide that it's bonding to smth
    probability_sum = np.sum(probability_for_each_nucleotide) #sums up all the probabilities, to give us the total percent
    #print(probability_sum)
    return 1-(probability_sum/(base_pair_probability_matrix.shape[0]-1)) #We then divide by the size of the array-1 (because the bpp of viennaRNA adds an extra row/col for nice formatting) also subtract by one to get the prob of being unpaired

In [18]:
#Can specify where start and end is with this method
#The index starts at 0, code auto modifies your input to work with the bpp that starts at index 1...
def probability_of_being_unpaired(base_pair_probability_matrix, start, end): #Gets single strandedness for nucleotide sequence from start to end index (end nucleotide not included)
    assert base_pair_probability_matrix.ndim == 2, "matrix must be two dimensional"
    assert base_pair_probability_matrix.shape[0] == base_pair_probability_matrix.shape[1], "matrix must be square"

    top_triangle_probability_matrix = np.triu(base_pair_probability_matrix, 1)#zeroes out the main diagonal of the matrix plus all the diagonals below it
    #Slice the matrix to do easier sum stuff (might be pointless but hey why not)
    sub_matrix = top_triangle_probability_matrix[start+1:end+1, :]#Starts at index 1, so we have to increment everything by 1 (0th nucleotide is 1st row in the matrix and so on)
    probability_for_each_nucleotide = np.sum(sub_matrix, axis=0)#Give us the probability of each nucleotide that it's bonding to smth
    probability_sum = np.sum(probability_for_each_nucleotide) #sums up all the probabilities, to give us the total percent
    #print(probability_sum) 
    return 1-(probability_sum/(end-start))

In [19]:
df.head()

,target_location,toehold_switch_sequence,target_sequence
0,6946,GGGGAAGAGUCUAUUGAGCUAGUUGGUAGUCCUAUACAGAAACAGA...,AGGACTACCAACTAGCTCAATAGACTCTTC
1,6805,GGGGUUUCAUUUUAUUCCUAUACUGGCUGCUUAAUACAGAAACAGA...,TAAGCAGCCAGTATAGGAATAAAATGAAAC
2,6804,GGGUUUCAUUUUAUUCCUAUACUGGCUGCUUAUAUACAGAAACAGA...,ATAAGCAGCCAGTATAGGAATAAAATGAAA
3,6771,GGGGACAAUUGAGAGAUUGUUACCAUAUAGCUAAUACAGAAACAGA...,TAGCTATATGGTAACAATCTCTCAATTGTC
4,6712,GGGCUAUUAUAUAUCCCUUUGUUGGGUUUAUACAUACAGAAACAGA...,GTATAAACCCAACAAAGGGATATATAATAG

In [20]:
def test_valid_notation(d): #just sees that every opening parenthesis has a closing parethesis (i.e is valid notation)
    q = deque()
    structure_present = False
    for let in d:
        if let == '(':
            q.append(let)
            structure_present = True 
        elif let == ')':
            if (len(q)==0):
                return 1 #if extra closed parethesis
            q.pop()
    if(len(q)==0):
        if structure_present is True:
            return 0 #if valid
        else:
            return 1 #There is no structure at all present. That isn't a loop so let's add an open parenthesis to see if the loop got shifted over
    return 2 #if extra open parethesis

In [21]:
#NOTE: Change to actual stem loop value locations 
def stem_loop_eval(s): #Stem loop region is 35-48 nucleotide inclusive
    start = 65
    end = 79
    strand_sub = s[start:end]
    ind = 1
    limit = 3 #Limit is 3 because seems like a good num i suppose
    result = test_valid_notation(strand_sub)
    #print(strand_sub)
    while result!=0 and ind<=limit: #there might be off by 1 errors, so we are gonna add up to the limit that many nueclotides to the sequence to try to get a valid sequence
        if result==1:
            start-=1
        else:
            end+=1
        strand_sub = s[start:end]
        #print(strand_sub) 
        result = test_valid_notation(strand_sub)
        #print(ind)
        ind+=1
    if result == 0:
        return True, start, end
    return False, -1, -1

In [22]:
def calculate_kmers(sequence, start, end, kmer_lengths=[3, 4, 5]):
    
    subsequence = sequence[start:end]

    kmer_counts = {}

    for k in kmer_lengths:
        for i in range(len(subsequence) - k + 1):
            kmer = subsequence[i:i+k]
            if kmer in kmer_counts:
                kmer_counts[kmer] += 1
            else:
                kmer_counts[kmer] = 1

    return kmer_counts

In [23]:
#This is used to calculate the table for the reporter genes, as the partition function calculations take absurdly long (the reporter sequence is way too big)
#So this method is used to make a table of data for these genes, and then the table is input into later methods
def long_list_seq_calc(seq, salt_list):
    value_list = [[] for i in range(1)]
    long_md = RNA.md()
    long_md.temperature = temp
    for i in salt_list:
        print('new concentration:', i, flush=True)
        long_md.salt = i
        long_fc = RNA.fold_compound(seq, long_md)
        [mfe_struct, mfe_energy] = long_fc.mfe()
        print("before pf",flush=True)
        long_fc.exp_params_rescale(mfe_energy)
        long_fc.pf()
        print("after pf", flush=True)
        ensemble_defect = long_fc.ensemble_defect(mfe_struct)
        [gc,at] = compute_AT_and_GC_percent(seq)
        base_pairs = long_fc.bpp()
        np_basepairs = np.asarray(base_pairs)
        single_strandedness = find_single_strandedness(np_basepairs)
        print(mfe_struct, mfe_energy, gc, at, ensemble_defect, single_strandedness)
        value_list.append([mfe_struct, mfe_energy, gc, at, ensemble_defect, single_strandedness])
    print(value_list[1:])
    return value_list[1:]

In [24]:
#Just used to insert the row of data that was just made in the calculate_table method into the right row in the huge datatable (Can probably optimize and take this out)
def fill_matrix(arr_loc, arr, data):
    for k in range(len(col_names)):
        # print(len(arr[arr_loc]))
        #print(len(data))
        arr[arr_loc][k] = data[k]

In [25]:
def test_for_enclosed_structure(structure, start_ind, length):
    end_ind = start_ind + length
    if(start_ind==0):
        raise Exception("Start index cannot be 0")
    start_ind -=1 #This is because we are going to start checking the structure before the start index for an enclosed structure

    increment_count = 0
    limit = 10

    # print(structure[start_ind:end_ind+1])

    while start_ind !=0 and structure[start_ind] != '(' and increment_count < limit:
        start_ind -=1
        increment_count +=1
        # print('decrementing left')
        # print(structure[start_ind:end_ind+1])

    if(structure[start_ind]!='('):
        # print("Not Valid")
        return False
    
    increment_count = 0

    while end_ind != len(structure)-1 and structure[end_ind] != ')' and increment_count<limit:
        end_ind +=1
        increment_count +=1
        # print("increasing right")
        # print(structure[start_ind:end_ind+1])
        
    if structure[end_ind] == ')':
        # print("Valid")
        return True
    # else:
    #     print("Not Valid")
    #     return False

In [26]:
def test_validity_of_rbs(riboswitch_sequence, riboswitch_structure):
    valid = False 
    index = None
    aug_limit = 15 #Relatively close to 10 + len of rbs. Can change later depending on needs

    rbs_index = riboswitch_sequence.find("AGGAGA") #This is the rbs sequence (ribosomal binding site, where the ribosome will bind to start transcribing the reporter gene)
    #print(rbs_index)

    if(rbs_index > 40 and rbs_index<110): #Shouldn't be located near the beginning or end unless smth wrong has occured
        if(test_for_enclosed_structure(riboswitch_structure, rbs_index, 6)):
            if(riboswitch_sequence.find("AUG", rbs_index)-rbs_index<=aug_limit): #There should be a start codon, or AUG, after the rbs. Check to see if there is one close by
                valid = True
                index = rbs_index
    return [valid,index]

In [27]:
#Calculates the datatable of the riboswitches (so we don't have to calculate it again) and then feed into calculate_table method
#Main difference is that it has to calculate data for the loop, and for the trigger which is fed into it
#Pass in the trigger as a df to do merge
def make_riboswitch_table(riboswitch_data_dataframe, name_of_dataframe, switch_col, trigger_length, trigger_df, subname_col = -1):
    row_counter = 0
    riboswitch_data_dataframe = riboswitch_data_dataframe.dropna()
    combined_riboswitch_trigger_dataframe = riboswitch_data_dataframe.merge(trigger_df, how='cross')
    display(combined_riboswitch_trigger_dataframe)
    def riboswitch_helper(row):
        nonlocal row_counter
        #print("Starting row:",row_counter,flush=True)
        if row_counter % 100000 == 0:
            print('We are starting:',row_counter/100000)
        if subname_col < 0:
            subname = None
        else:
            subname = row.iloc[subname_col]
        
        switch_sequence = transcribe_dna_to_rna(row.iloc[-1]+ row.iloc[switch_col]) #Trigger should hopefully always be the last column, will do testing later as this is hard coded value which is bad...
        #print(switch_sequence)
        switch_fc = RNA.fold_compound(switch_sequence, md)
        [switch_mfe_structure, switch_mfe] = switch_fc.mfe()
        #print(switch_mfe_structure)
        [switch_propensity_struct, switch_propensity_energy] = switch_fc.pf()
        [gc,at] = compute_AT_and_GC_percent(switch_sequence)

        switch_ensemble_defect = switch_fc.ensemble_defect(switch_mfe_structure)
        switch_basepairs = switch_fc.bpp()
        switch_np_basepairs = np.asarray(switch_basepairs)
        switch_single_strandedness = find_single_strandedness(switch_np_basepairs)
        trigger_single_strandedness = probability_of_being_unpaired(switch_np_basepairs, 0, trigger_length)
        trigger_struct = switch_mfe_structure[0:trigger_length]
        kmer_dict = calculate_kmers(switch_sequence, 0, len(switch_sequence))

        [rbs_validity, rbs_index] = test_validity_of_rbs(switch_sequence, switch_mfe_structure)
        #print("Done with row:", row_counter, flush=True)
        row_counter+=1
        return name_of_dataframe, subname, row_counter//(len(trigger_df)),switch_sequence, switch_mfe_structure, switch_mfe, gc, at, switch_ensemble_defect, switch_single_strandedness, trigger_single_strandedness, trigger_struct, kmer_dict, rbs_validity, rbs_index


    return combined_riboswitch_trigger_dataframe.apply(riboswitch_helper, axis=1, result_type = 'expand')

In [28]:
#same as above but for target and less data needing to be computed
def make_target_table(target_data_dataframe, name_of_dataframe, target_col, location_col = -1):
    
    target_data_dataframe = target_data_dataframe.dropna()

    def target_helper(row):
        if location_col<0:
            location = None
        else:
            location = row.iloc[location_col]
        target_sequence = transcribe_dna_to_rna(row.iloc[target_col])
        target_fc = RNA.fold_compound(target_sequence, md)
        [target_mfe_structure, target_mfe] = target_fc.mfe()
        [target_propensity_struct, switch_propensity_energy] = target_fc.pf()
        [gc,at] = compute_AT_and_GC_percent(target_sequence)

        target_ensemble_defect = target_fc.ensemble_defect(target_mfe_structure)
        target_basepairs = target_fc.bpp()
        target_np_basepairs = np.asarray(target_basepairs)
        target_single_strandedness = find_single_strandedness(target_np_basepairs)
        kmer_dict = calculate_kmers(target_sequence, 0, len(target_sequence))
        
        return name_of_dataframe, location, target_sequence, target_mfe_structure, target_mfe, gc, at, target_ensemble_defect, target_single_strandedness, kmer_dict
    
    return target_data_dataframe.apply(target_helper, axis = 1, result_type = 'expand')

In [29]:
#Just testing to make sure it all works. Uncomment if you want

# df_test2 = df
# df_test2 = df_test2.dropna()
# df_testyep = pd.DataFrame()
# md.salt = .1
# df_testyep[target_table_names] = make_target_table(df_test2, 'testing', 2, 0)
# display(df_testyep)
# md.salt = 1.0
# df_testyep[target_table_names] = make_target_table(df_test2, 'testing', 2, 0)
# display(df_testyep)
# print(len(df_testyep))
# df_testyep = make_target_table(df_testyep, 'testing', 2, 0)
# md.salt = 0.5
# display(df_testyep)
# df_test2 = df_test2[df_test2.columns[2],target_table_names]
# display(df_test2)
# df_test2.columns = [df_test2.columns[2],target_table_names]
# display(df_test2)

In [30]:
#Link to the green data sheet
green_sheet_link = 'https://docs.google.com/spreadsheets/d/1mYZjaF14teogWxWKKhV92_bB-XhE08jU/edit?gid=488230874#gid=488230874'
green_sheet_dataframe = pd.read_csv('Riboswitch sequences.xlsx - Sheet1.csv', header = None, skiprows=1)
green_sheet_dataframe.head()
display(green_sheet_dataframe[1])

0      GGGUCUUAUCUUAUCUAUCUCGUUUAUCCCUGCAUACAGAAACAGA...
1      GGGAGUUUGAUUACAUUGUCGUUUAGUUUAGUGAUACAUAAACAGA...
2      GGGAUCUAUUACUACUUACCAUUGUCUUGCUCUAUACAGAAACAGA...
3      GGGCGAUUAUGGAUUAGAGCUCCGUUUACUGUCAUACAAGAACAGA...
4      GGGUAUGUAAUUGAUUUGGCUUCUGUUAGUUUCAUACAAGAACAGA...
                             ...
176    GGGAUAAGAUGAGAUAAUGAGAUGAAGUUGGCGGACAGAGGAGACG...
177    GGGAUCGAUGUAUGUAGUUAUUGUAUGUCCGUGAACAGAGGAGACA...
178    GGGAAUGGAAUGAGACGUGAGAUAAUGUAGUGAGACAGAGGAGAUC...
179    GGGUGAUUUGAUUGUAGGUGGCUGGUCGUGUAAGACAGAGGAGAUU...
180    GGGAGUAAAUGAAUAAGGUGAUAGAUGUGUAUGGACAGAGGAGACA...
Name: 1, Length: 181, dtype: object

In [31]:
# #Used for testing to make sure it's all set and good
# df_3 = pd.DataFrame()
# df_3[riboswitch_table_names] = make_riboswitch_table(green_sheet_dataframe, 'Green', 1, 30, trigger_generator(full_target_data,1),0)
# display(df_3)

In [32]:
#Due to limitations of how binding works and how we make complexes, the target will always be first then the trigger
#We can just check the trigger to see how many ')' there are to see how many bind to the target correctly
#If there is an '(' in the trigger, it will always bind to the next ')' so that's why we don't add it to num_binds when that happens
#look up dot parethesis structure notation for more info
def trigger_target_binding(struct, len): #len is length of target or trigger (they should be the same size)
    num_binds = 0
    open_trigger_nucleotides = 0
    # print(struct[0:60])
    for i in range(len): #Trigger should be the len of target and 0+len nucleotides into the structure
        if struct[i+len] == '(': 
            open_trigger_nucleotides+=1
        elif struct[i+len] == ')': 
            if open_trigger_nucleotides>0:
                open_trigger_nucleotides-=1
            else:
                num_binds +=1
    percent_bind = num_binds/len
    # print(struct[0:len])
    # print(struct[len:len*2])
    # print(num_binds)
    return percent_bind

In [33]:
#These are the col names of the table being filled in, later the order of the columns will be changed according to the 'finished data names up top
col_names = ['label','salt_molarity', 'temperature (Celsius)', 'name_of_riboswitch_data', 'name_of_target_data','riboswitch_subcategory',
             'switch_row','trigger_row','target_row', 'target_location', 'trigger_location',
             'riboswitch_sequence', 'trigger_sequence','target_sequence', 'target_trigger_complex','reporter_sequence', 'switch_structure', 'target_structure',
             'switch_energy','target_energy', 'trigger_single_strandedness', 'trigger_structure',
             'switch_kmers', 'target_kmers', 'rbs_validity','rbs_location',
             'valid_loop', 'loop_sequence', 'loop_structure',
            'loop_energy','complex_nucelotides','complex_structure','complex_energy',
            'complex_gc', 'complex_at','switch_gc','switch_at','target_gc','target_at','switch_ensemble_defect','target_ensemble_defect','complex_ensemble_defect',
            'switch_single_strandedness','target_single_strandedness','complex_single_strandedness', 'complex_kmers',
            'reporter_structure', 'reporter_energy', 'reporter_gc', 'reporter_at', 'reporter_ensemble_defect', 'reporter_single_strandedness', 'trigger_target_binding_percentage']
print(col_names)
len(col_names)

['label', 'salt_molarity', 'temperature (Celsius)', 'name_of_riboswitch_data', 'name_of_target_data', 'riboswitch_subcategory', 'switch_row', 'trigger_row', 'target_row', 'target_location', 'trigger_location', 'riboswitch_sequence', 'trigger_sequence', 'target_sequence', 'target_trigger_complex', 'reporter_sequence', 'switch_structure', 'target_structure', 'switch_energy', 'target_energy', 'trigger_single_strandedness', 'trigger_structure', 'switch_kmers', 'target_kmers', 'rbs_validity', 'rbs_location', 'valid_loop', 'loop_sequence', 'loop_structure', 'loop_energy', 'complex_nucelotides', 'complex_structure', 'complex_energy', 'complex_gc', 'complex_at', 'switch_gc', 'switch_at', 'target_gc', 'target_at', 'switch_ensemble_defect', 'target_ensemble_defect', 'complex_ensemble_defect', 'switch_single_strandedness', 'target_single_strandedness', 'complex_single_strandedness', 'complex_kmers', 'reporter_structure', 'reporter_energy', 'reporter_gc', 'reporter_at', 'reporter_ensemble_defect', 'reporter_single_strandedness', 'trigger_target_binding_percentage']

53

Todo: Make it so the trigger data is actually inserted as data (trigger row and also trigger sequence)
Make an actual loop that goes through everything. It should be the same thing of now one loop, with target_data being a %switch_size type thing. 
Everything else should be the same though... and be sure to change the column names afterward too

In [34]:
#Feed in riboswitch df, and target df, alongside with the column #s for everything because this gotta be
def calculate_table(riboswitch_data, name_of_riboswitch_dataframe, switch_col, trigger_length, target_data, name_of_target_dataframe, target_col, csv_names, reporter_seq, 
                    reporter_table, label, location_col = -1, subname_col = -1):
    print("started method", flush=True)
    riboswitch_data = riboswitch_data.dropna()
    target_data = target_data.dropna()
    trigger_data = trigger_generator(target_data, target_col, location_col)
    trigger_sequences_series = trigger_data['trigger_sequence']
    display(target_data)
    display(trigger_data)
    # display(trigger_sequences_series.to_frame())
    ribo_size = len(riboswitch_data)
    switch_size = len(target_data)
    vArr = [[0 for i in range (len(col_names))] for j in range (ribo_size*switch_size)] #fix later lol
    test = deepcopy(vArr)
    full_table = [[] for i in range(1)]
    #0 is salt
    #1 is temperature
    #2 is switch row
    #3 is target row
    #4 is target location
    #5 is toehold switch sequence
    #6 is target sequence
    #7 is switch mfe struct
    #8 is target mfe struct
    #9 is switch energy
    #10 is target energy
    #11 is valid stem loop
    #12 is stem loop sequence
    #13 is stem loop structure
    #14 is stem loop energy
    #15 is complex nucelotides
    #16 is complex structure
    #17 is complex visualization
    #18 is complex energy
    #19 is complex gc count
    #20 is switch gc count
    #21 is target gc count
    #22 is switch ensemble defect
    #23 is target ensemble defect
    #24 is complex ensemble defect
    #25 is switch single strandness
    #26 is target single strandness
    #27 is complex single strandness
    print("finished making the table",flush=True)
    for i in range(len(salt_concentrations_list)):

        md.salt = salt_molarity = salt_concentrations_list[i]
        print("new concetration now", salt_molarity, flush=True)


        ribocopy_df = pd.DataFrame()
        targetcopy_df = pd.DataFrame()
        #Another hard coded value of 1 into iloc... should be ok as trigger sequences should only be in the 1th index
        ribocopy_df[riboswitch_table_names] = make_riboswitch_table(riboswitch_data, name_of_riboswitch_dataframe, switch_col, trigger_length, trigger_sequences_series,subname_col) 
        targetcopy_df[target_table_names] = make_target_table(target_data, name_of_target_dataframe, target_col, location_col)


        print("preliminary data done and dusted", flush=True)
        print('Reporter row data is:', reporter_table[i])
        for j in range(len(ribocopy_df)):
            x = j
            y = j%switch_size #y will be the trigger and target row in the positive case
            riboswitch_row = j//switch_size
            switch_struct = ribocopy_df.at[x,'switch_structure']
            switch_seq = ribocopy_df.at[x,'riboswitch_sequence']
            switch_subname = ribocopy_df.at[x,'riboswitch_subcategory']
            if(j%switch_size==0):
                print('new riboswitch yeppers:', riboswitch_row)
            data_list = []
            target_seq = targetcopy_df.at[y,'target_sequence']
            trigger_seq = trigger_data.at[y,'trigger_sequence']
            target_struct = targetcopy_df.at[y,'target_structure']
            arr_loc = j

            #data 0-10
            #adding salt, temperature, switch row, target row, target location, toehold switch sequence, target sequence, switch mfe structure, target mfe structure, switch energy, and target energy to list
            data_list.extend([label, salt_molarity, temp, name_of_riboswitch_dataframe, name_of_target_dataframe, switch_subname,riboswitch_row, y, y, 
                                targetcopy_df.at[y, 'target_location'], trigger_data.at[y,'Location'],switch_seq, 
                                trigger_seq, target_seq, target_seq+trigger_seq,reporter_seq, switch_struct, target_struct, ribocopy_df.at[x,'switch_energy'], 
                                targetcopy_df.at[y,'target_energy'], ribocopy_df.at[x,'trigger_single_strandedness'], ribocopy_df.at[x,'trigger_structure'],
                                ribocopy_df.at[x, 'switch_kmers'], targetcopy_df.at[y, 'target_kmers'], ribocopy_df.at[x, 'rbs_validity'], ribocopy_df.at[x, 'rbs_location']])

            #This is scuffed, there should be a better way but this will do for now
            #This evaluates the stem loop and its free energy, if it's valid
            outcome = stem_loop_eval(switch_struct)
            #Add if the loop is valid (#11)
            validity = outcome[0]
            data_list.append(validity)

            #now add the loop sequence, structure, and energy if applicable (#12-14)

            if(validity==False): #if not valid from stem loop test 
                data_list.extend(['N/A', 'N/A', 'N/A'])
            else:
                #we use substrings of the switches sequence and structure to get the loop structure and sequence
                sub_seq = switch_seq[outcome[1]:outcome[2]]
                sub_struct = switch_struct[outcome[1]:outcome[2]]
                #print(sub_struct)
                data_list.extend([sub_seq, sub_struct, RNA.fold_compound(sub_seq,md).mfe()[1]])
            
            
            #Add the complex sequence + subsequence of reporter gene (#15)
            short_reporter = reporter_seq[:10] #we can't use the entire subseqence because that blows up everything with pf. Only 10 base pairs
            data_list.append(target_seq+switch_seq+short_reporter)

            complex_sequence = target_seq+switch_seq+short_reporter

            #Add the reporter gene to the switch
            # full_riboswitch = switch_seq+short_reporter Note: unused as full riboswitch too large
            #Current NOTE: We don't need to replace the T's with U anymore
            # Old NOTE SOME OF THE SEQUENCES HAVE T's IN THEM INSTEAD OF U's... WE GOTTA REPLACE THEM, Original is still listed in table
            # replaced_target_seq = target_seq.replace('T','U')
            # new_switch_seq = full_riboswitch.replace('T','U')
            # replaced_short_reporter = short_reporter.replace('T','U')

            # print(len(target_seq+new_switch_seq))

            fc = RNA.fold_compound(target_seq+'&'+switch_seq+'&'+short_reporter, md)
            (v_complex_struct, v_complex_mfe) = fc.mfe()
            #Add the structure, visualization structure, mfe energy, complex gc count, switch gc count, and target gc count (#16-21)
            #NOTE: See if we want to compute AT GC for the WHOLE complex or with just the short reporter later 
            [complex_gc, complex_at] = compute_AT_and_GC_percent(target_seq+switch_seq+short_reporter)
            data_list.extend([v_complex_struct, v_complex_mfe, complex_gc, complex_at,
                                ribocopy_df.at[x,'switch_gc'],ribocopy_df.at[x, 'switch_at'], targetcopy_df.at[y, 'target_gc'], targetcopy_df.at[y, 'target_at']])
            
            #ensemble defect/parititon function calculations
            #We add the switch, target, and complex ensemble defect here (#22-24)
            (complex_propensity, complex_ensemble_energy) = fc.pf()
            data_list.extend([ribocopy_df.at[x, 'switch_ensemble_defect'], targetcopy_df.at[y, 'target_ensemble_defect'], fc.ensemble_defect(v_complex_struct)])

            #Calculate and add the switch, target, and complex single strandedness (#24-27)
            #NOTE: Removing the below for now because pf doesn't work well with big sequences, it's broken anyways
            complex_bpp = fc.bpp()
            np_complex = np.asarray(complex_bpp)
            data_list.extend([ribocopy_df.at[x, 'switch_single_strandedness'],targetcopy_df.at[y, 'target_single_strandedness'], find_single_strandedness(np_complex)])

            complex_kmer_dict = calculate_kmers(complex_sequence, 0, len(complex_sequence))
            data_list.extend([complex_kmer_dict])

            data_list.extend(reporter_table[i])
            
            length_of_trigger = 30 #NOTE: make it a changeable feature later
            data_list.extend([trigger_target_binding(v_complex_struct,length_of_trigger)])

            fill_matrix(arr_loc, vArr, data_list)
            #fill_matrix(arr_loc, test, data_list)
            full_table.append(data_list)
        concentration_data = pd.DataFrame(vArr)
        concentration_data.columns = col_names
        concentration_data = concentration_data[finished_data_names]
        display(concentration_data)
        concentration_data.to_csv(csv_names[i])
        # print("this is the array")
        # display(pd.DataFrame(vArr))
        # print('this is the full_table')
        # display(pd.DataFrame(full_table))

            

    full_table = full_table[1:] #To get rid of the first empty row
    #full_table.insert(0, col_names)
    # display(full_table)
    #print(vArr)

    #NOTE: ADD A RETURN 
    
    results = pd.DataFrame(full_table)
    results.columns = col_names
    display(results)
    results = results[finished_data_names]
    display(results)
    return results
    #testing = pd.DataFrame(test)

In [35]:
# #Feed in riboswitch df, and target df, alongside with the column #s for everything because this gotta be
# def calculate_table(riboswitch_data, name_of_riboswitch_dataframe, switch_col, trigger_length, target_data, name_of_target_dataframe, target_col, csv_names, reporter_seq, 
#                     reporter_table, location_col = -1, subname_col = -1):
#     print("started method", flush=True)
#     riboswitch_data = riboswitch_data.dropna()
#     target_data = target_data.dropna()
#     trigger_data = trigger_generator(target_data, target_col, location_col)
#     ribo_size = len(riboswitch_data)
#     switch_size = len(target_data)
#     vArr = [[0 for i in range (len(col_names))] for j in range (ribo_size*switch_size)] #fix later lol
#     test = deepcopy(vArr)
#     full_table = [[] for i in range(1)]
#     #0 is salt
#     #1 is temperature
#     #2 is switch row
#     #3 is target row
#     #4 is target location
#     #5 is toehold switch sequence
#     #6 is target sequence
#     #7 is switch mfe struct
#     #8 is target mfe struct
#     #9 is switch energy
#     #10 is target energy
#     #11 is valid stem loop
#     #12 is stem loop sequence
#     #13 is stem loop structure
#     #14 is stem loop energy
#     #15 is complex nucelotides
#     #16 is complex structure
#     #17 is complex visualization
#     #18 is complex energy
#     #19 is complex gc count
#     #20 is switch gc count
#     #21 is target gc count
#     #22 is switch ensemble defect
#     #23 is target ensemble defect
#     #24 is complex ensemble defect
#     #25 is switch single strandness
#     #26 is target single strandness
#     #27 is complex single strandness
#     print("finished making the table",flush=True)
#     for i in range(len(salt_concentrations_list)):

#         md.salt = salt_molarity = salt_concentrations_list[i]
#         print("new concetration now", salt_molarity, flush=True)


#         ribocopy_df = pd.DataFrame()
#         targetcopy_df = pd.DataFrame()
#         #Another hard coded value of 0 into iloc... should be ok as trigger sequences should only be in the 0th index
#         ribocopy_df[riboswitch_table_names] = make_riboswitch_table(riboswitch_data, name_of_riboswitch_dataframe, switch_col, trigger_length, trigger_data.iloc[0].to_frame(),subname_col) 
#         targetcopy_df[target_table_names] = make_target_table(target_data, name_of_target_dataframe, target_col, location_col)


#         print("preliminary data done and dusted", flush=True)
#         print('Reporter row data is:', reporter_table[i])
#         for x in range(ribo_size):
#             switch_struct = ribocopy_df.at[x,'switch_structure']
#             switch_seq = ribocopy_df.at[x,'riboswitch_sequence']
#             switch_subname = ribocopy_df.at[x,'riboswitch_subcategory']
#             print('new riboswitch yeppers:', x)
#             for y in range(switch_size):
#                 print("Target:", y)
#                 data_list = []
#                 target_seq = targetcopy_df.at[y,'target_sequence']
#                 target_struct = targetcopy_df.at[y,'target_structure']
#                 arr_loc = x * switch_size + y

#                 #data 0-10
#                 #adding salt, temperature, switch row, target row, target location, toehold switch sequence, target sequence, switch mfe structure, target mfe structure, switch energy, and target energy to list
#                 data_list.extend([salt_molarity, temp, name_of_riboswitch_dataframe, name_of_target_dataframe, switch_subname,x, y, 
#                                   targetcopy_df.at[y, 'target_location'], switch_seq, 
#                                   target_seq, reporter_seq, switch_struct, target_struct, ribocopy_df.at[x,'switch_energy'], 
#                                   targetcopy_df.at[y,'target_energy'], ribocopy_df.at[x,'trigger_single_strandedness'], ribocopy_df.at[x,'trigger_structure'],
#                                   ribocopy_df.at[x, 'switch_kmers'], targetcopy_df.at[y, 'target_kmers'], ribocopy_df.at[x, 'rbs_validity'], ribocopy_df.at[x, 'rbs_location']])

#                 #This is scuffed, there should be a better way but this will do for now
#                 #This evaluates the stem loop and its free energy, if it's valid
#                 outcome = stem_loop_eval(switch_struct)
#                 #Add if the loop is valid (#11)
#                 validity = outcome[0]
#                 data_list.append(validity)

#                 #now add the loop sequence, structure, and energy if applicable (#12-14)

#                 if(validity==False): #if not valid from stem loop test 
#                     data_list.extend(['N/A', 'N/A', 'N/A'])
#                 else:
#                     #we use substrings of the switches sequence and structure to get the loop structure and sequence
#                     sub_seq = switch_seq[outcome[1]:outcome[2]]
#                     sub_struct = switch_struct[outcome[1]:outcome[2]]
#                     #print(sub_struct)
#                     data_list.extend([sub_seq, sub_struct, RNA.fold_compound(sub_seq,md).mfe()[1]])
                
                
#                 #Add the complex sequence + subsequence of reporter gene (#15)
#                 short_reporter = reporter_seq[:10] #we can't use the entire subseqence because that blows up everything with pf. Only 10 base pairs
#                 data_list.append(target_seq+switch_seq+short_reporter)

#                 complex_sequence = target_seq+switch_seq+short_reporter

#                 #Add the reporter gene to the switch
#                 # full_riboswitch = switch_seq+short_reporter Note: unused as full riboswitch too large
#                 #Current NOTE: We don't need to replace the T's with U anymore
#                 # Old NOTE SOME OF THE SEQUENCES HAVE T's IN THEM INSTEAD OF U's... WE GOTTA REPLACE THEM, Original is still listed in table
#                 # replaced_target_seq = target_seq.replace('T','U')
#                 # new_switch_seq = full_riboswitch.replace('T','U')
#                 # replaced_short_reporter = short_reporter.replace('T','U')
    
#                 # print(len(target_seq+new_switch_seq))

#                 fc = RNA.fold_compound(target_seq+'&'+switch_seq+'&'+short_reporter, md)
#                 (v_complex_struct, v_complex_mfe) = fc.mfe()
#                 #Add the structure, visualization structure, mfe energy, complex gc count, switch gc count, and target gc count (#16-21)
#                 #NOTE: See if we want to compute AT GC for the WHOLE complex or with just the short reporter later 
#                 [complex_gc, complex_at] = compute_AT_and_GC_percent(target_seq+switch_seq+short_reporter)
#                 data_list.extend([v_complex_struct, v_complex_mfe, complex_gc, complex_at,
#                                   ribocopy_df.at[x,'switch_gc'],ribocopy_df.at[x, 'switch_at'], targetcopy_df.at[y, 'target_gc'], targetcopy_df.at[y, 'target_at']])
                
#                 #ensemble defect/parititon function calculations
#                 #We add the switch, target, and complex ensemble defect here (#22-24)
#                 (complex_propensity, complex_ensemble_energy) = fc.pf()
#                 data_list.extend([ribocopy_df.at[x, 'switch_ensemble_defect'], targetcopy_df.at[y, 'target_ensemble_defect'], fc.ensemble_defect(v_complex_struct)])

#                 #Calculate and add the switch, target, and complex single strandedness (#24-27)
#                 #NOTE: Removing the below for now because pf doesn't work well with big sequences, it's broken anyways
#                 complex_bpp = fc.bpp()
#                 np_complex = np.asarray(complex_bpp)
#                 data_list.extend([ribocopy_df.at[x, 'switch_single_strandedness'],targetcopy_df.at[y, 'target_single_strandedness'], find_single_strandedness(np_complex)])

#                 complex_kmer_dict = calculate_kmers(complex_sequence, 0, len(complex_sequence))
#                 data_list.extend([complex_kmer_dict])

#                 data_list.extend(reporter_table[i])
                
#                 length_of_trigger = 30 #NOTE: make it a changeable feature later
#                 data_list.extend([trigger_target_binding(v_complex_struct,length_of_trigger)])

#                 fill_matrix(arr_loc, vArr, data_list)
#                 #fill_matrix(arr_loc, test, data_list)
#                 full_table.append(data_list)
#         concentration_data = pd.DataFrame(vArr)
#         concentration_data.columns = col_names
#         concentration_data = concentration_data[finished_data_names]
#         display(concentration_data)
#         concentration_data.to_csv(csv_names[i])
#         # print("this is the array")
#         # display(pd.DataFrame(vArr))
#         # print('this is the full_table')
#         # display(pd.DataFrame(full_table))

            

#     full_table = full_table[1:] #To get rid of the first empty row
#     #full_table.insert(0, col_names)
#     # display(full_table)
#     #print(vArr)

#     #NOTE: ADD A RETURN 
    
#     results = pd.DataFrame(full_table)
#     results.columns = col_names
#     display(results)
#     results = results[finished_data_names]
#     display(results)
#     return results
#     #testing = pd.DataFrame(test)

In [ ]:
#Note: This line might take a while in code. You might have to stop this line from running, don't clear kernel, and then rerun it to see outputs. It's strange
lacZ_preliminary_table = long_list_seq_calc(lacZ_seq,salt_concentrations_list)

new concentration: 0

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

kn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error

expn singularity error


KeyboardInterrupt:

In [39]:
salt_concentrations_list = [0.1,1.0]

In [40]:
cherry_preliminary_table = long_list_seq_calc(cherry_seq,salt_concentrations_list)

new concentration: 0.1
before pf
after pf
.......((..(((.((((((.......(((((...........((((((((.(((((.(.....).))))).))...)))))))))))(((........))).(((((((((((.(((((((((.......(((((((((.(......))))..)))).))..))))))))).).)))).))))))((((((...)))))).....((((((((.((((....)))))))))))).((((.(((((.(.(((.(((((((((((((((.((.......)).))))))))))))......((.....)).))).))).).))))).)))).((........)).)))))))))))...(((((..((((((......((((..((...))..))))........((((..((((((.(((..............)))))))))))))((((((((.(.(.((.....))))))))).))).((((....)))).......(((..((((...(((..(((.(((((..........))))).(((....))).)))....))).....))))..))).....((((((((((.....((((((.....))).)))....((((.......)))).........(((((......))))))))))))).))((((((........))))))))))))..)))))........ -297.82000732421875 0.620253164556962 0.379746835443038 0.3396698841262058 0.6978535461294293
new concentration: 1.0
before pf
after pf
.......((..(((.((((((.......(((((.((......))((((((((.(((((.(.....).))))).))...)))))))))))(((........))).(((((((((((.(((((((((.......(((((((((.(......))))..)))).))..))))))))).).)))).))))))((((((...)))))).....((((((((.((((....)))))))))))).((((.(((((.(.(((.(((((((((((((((.((.......)).))))))))))))......((.....)).))).))).).))))).)))).((........)).)))))))))))...(((((..((((((......((((..((...))..)))).......(((((..((((((.((....(....)...))...)))))))))))...((((.(.(((..((((((((((((...(((((((...((((.((.....(((..((((...(((..(((.(((((..........))))).(((....))).)))....))).....))))..)))..))))))))))))).....((((((.....))).)))....((((.......))))......)).))).))....)))))..))).).))))((((((........))))))))))))..)))))........ -341.07000732421875 0.620253164556962 0.379746835443038 0.37567186213465853 0.6926941478000694
[['.......((..(((.((((((.......(((((...........((((((((.(((((.(.....).))))).))...)))))))))))(((........))).(((((((((((.(((((((((.......(((((((((.(......))))..)))).))..))))))))).).)))).))))))((((((...)))))).....((((((((.((((....)))))))))))).((((.(((((.(.(((.(((((((((((((((.((.......)).))))))))))))......((.....)).))).))).).))))).)))).((........)).)))))))))))...(((((..((((((......((((..((...))..))))........((((..((((((.(((..............)))))))))))))((((((((.(.(.((.....))))))))).))).((((....)))).......(((..((((...(((..(((.(((((..........))))).(((....))).)))....))).....))))..))).....((((((((((.....((((((.....))).)))....((((.......)))).........(((((......))))))))))))).))((((((........))))))))))))..)))))........', -297.82000732421875, 0.620253164556962, 0.379746835443038, 0.3396698841262058, 0.6978535461294293], ['.......((..(((.((((((.......(((((.((......))((((((((.(((((.(.....).))))).))...)))))))))))(((........))).(((((((((((.(((((((((.......(((((((((.(......))))..)))).))..))))))))).).)))).))))))((((((...)))))).....((((((((.((((....)))))))))))).((((.(((((.(.(((.(((((((((((((((.((.......)).))))))))))))......((.....)).))).))).).))))).)))).((........)).)))))))))))...(((((..((((((......((((..((...))..)))).......(((((..((((((.((....(....)...))...)))))))))))...((((.(.(((..((((((((((((...(((((((...((((.((.....(((..((((...(((..(((.(((((..........))))).(((....))).)))....))).....))))..)))..))))))))))))).....((((((.....))).)))....((((.......))))......)).))).))....)))))..))).).))))((((((........))))))))))))..)))))........', -341.07000732421875, 0.620253164556962, 0.379746835443038, 0.37567186213465853, 0.6926941478000694]]

In [41]:
green_ms2_cherry_results = calculate_table(green_sheet_dataframe, 'Green Riboswitches', 1, 30, ms2_data, 'MS2 Virus', 0, ms2_green_cherry_csv_names, cherry_seq, cherry_preliminary_table, 1,1,0)
green_ms2_cherry_results.to_csv('large_green_MS2_data.csv')

started method

      RNA polymerase Sequence (30bp)  Location
0     TGTCGAAGACAACAAAGAAGTTCAACTCTT      1761
1     GTCGAAGACAACAAAGAAGTTCAACTCTTT      1762
2     TCGAAGACAACAAAGAAGTTCAACTCTTTA      1763
3     CGAAGACAACAAAGAAGTTCAACTCTTTAT      1764
4     GAAGACAACAAAGAAGTTCAACTCTTTATG      1765
...                              ...       ...
1633  GTAGCTGACCGAGGGACCCCCGTAAACGGG      3394
1634  TAGCTGACCGAGGGACCCCCGTAAACGGGG      3395
1635  AGCTGACCGAGGGACCCCCGTAAACGGGGT      3396
1636  GCTGACCGAGGGACCCCCGTAAACGGGGTG      3397
1637  CTGACCGAGGGACCCCCGTAAACGGGGTGG      3398

[1638 rows x 2 columns]

      Location                trigger_sequence
0         1761  AAGAGUUGAACUUCUUUGUUGUCUUCGACA
1         1762  AAAGAGUUGAACUUCUUUGUUGUCUUCGAC
2         1763  UAAAGAGUUGAACUUCUUUGUUGUCUUCGA
3         1764  AUAAAGAGUUGAACUUCUUUGUUGUCUUCG
4         1765  CAUAAAGAGUUGAACUUCUUUGUUGUCUUC
...        ...                             ...
1633      3394  CCCGUUUACGGGGGUCCCUCGGUCAGCUAC
1634      3395  CCCCGUUUACGGGGGUCCCUCGGUCAGCUA
1635      3396  ACCCCGUUUACGGGGGUCCCUCGGUCAGCU
1636      3397  CACCCCGUUUACGGGGGUCCCUCGGUCAGC
1637      3398  CCACCCCGUUUACGGGGGUCCCUCGGUCAG

[1638 rows x 2 columns]

finished making the table
new concetration now 0.1

,0,1,trigger_sequence
0,forward engineered 4,GGGUCUUAUCUUAUCUAUCUCGUUUAUCCCUGCAUACAGAAACAGA...,AAGAGUUGAACUUCUUUGUUGUCUUCGACA
1,forward engineered 4,GGGUCUUAUCUUAUCUAUCUCGUUUAUCCCUGCAUACAGAAACAGA...,AAAGAGUUGAACUUCUUUGUUGUCUUCGAC
2,forward engineered 4,GGGUCUUAUCUUAUCUAUCUCGUUUAUCCCUGCAUACAGAAACAGA...,UAAAGAGUUGAACUUCUUUGUUGUCUUCGA
3,forward engineered 4,GGGUCUUAUCUUAUCUAUCUCGUUUAUCCCUGCAUACAGAAACAGA...,AUAAAGAGUUGAACUUCUUUGUUGUCUUCG
4,forward engineered 4,GGGUCUUAUCUUAUCUAUCUCGUUUAUCCCUGCAUACAGAAACAGA...,CAUAAAGAGUUGAACUUCUUUGUUGUCUUC
...,...,...,...
296473,144 orthoganal first gen,GGGAGUAAAUGAAUAAGGUGAUAGAUGUGUAUGGACAGAGGAGACA...,CCCGUUUACGGGGGUCCCUCGGUCAGCUAC
296474,144 orthoganal first gen,GGGAGUAAAUGAAUAAGGUGAUAGAUGUGUAUGGACAGAGGAGACA...,CCCCGUUUACGGGGGUCCCUCGGUCAGCUA
296475,144 orthoganal first gen,GGGAGUAAAUGAAUAAGGUGAUAGAUGUGUAUGGACAGAGGAGACA...,ACCCCGUUUACGGGGGUCCCUCGGUCAGCU
296476,144 orthoganal first gen,GGGAGUAAAUGAAUAAGGUGAUAGAUGUGUAUGGACAGAGGAGACA...,CACCCCGUUUACGGGGGUCCCUCGGUCAGC
296477,144 orthoganal first gen,GGGAGUAAAUGAAUAAGGUGAUAGAUGUGUAUGGACAGAGGAGACA...,CCACCCCGUUUACGGGGGUCCCUCGGUCAG

We are starting: 0.0
We are starting: 1.0
We are starting: 2.0
preliminary data done and dusted
Reporter row data is: ['.......((..(((.((((((.......(((((...........((((((((.(((((.(.....).))))).))...)))))))))))(((........))).(((((((((((.(((((((((.......(((((((((.(......))))..)))).))..))))))))).).)))).))))))((((((...)))))).....((((((((.((((....)))))))))))).((((.(((((.(.(((.(((((((((((((((.((.......)).))))))))))))......((.....)).))).))).).))))).)))).((........)).)))))))))))...(((((..((((((......((((..((...))..))))........((((..((((((.(((..............)))))))))))))((((((((.(.(.((.....))))))))).))).((((....)))).......(((..((((...(((..(((.(((((..........))))).(((....))).)))....))).....))))..))).....((((((((((.....((((((.....))).)))....((((.......)))).........(((((......))))))))))))).))((((((........))))))))))))..)))))........', -297.82000732421875, 0.620253164556962, 0.379746835443038, 0.3396698841262058, 0.6978535461294293]
new riboswitch yeppers: 0
new riboswitch yeppers: 1
new riboswitch yeppers: 2
new riboswitch yeppers: 3
new riboswitch yeppers: 4
new riboswitch yeppers: 5
new riboswitch yeppers: 6
new riboswitch yeppers: 7
new riboswitch yeppers: 8
new riboswitch yeppers: 9
new riboswitch yeppers: 10
new riboswitch yeppers: 11
new riboswitch yeppers: 12
new riboswitch yeppers: 13
new riboswitch yeppers: 14
new riboswitch yeppers: 15
new riboswitch yeppers: 16
new riboswitch yeppers: 17
new riboswitch yeppers: 18
new riboswitch yeppers: 19
new riboswitch yeppers: 20
new riboswitch yeppers: 21
new riboswitch yeppers: 22
new riboswitch yeppers: 23
new riboswitch yeppers: 24
new riboswitch yeppers: 25
new riboswitch yeppers: 26
new riboswitch yeppers: 27
new riboswitch yeppers: 28
new riboswitch yeppers: 29
new riboswitch yeppers: 30
new riboswitch yeppers: 31
new riboswitch yeppers: 32
new riboswitch yeppers: 33
new riboswitch yeppers: 34
new riboswitch yeppers: 35
new riboswitch yeppers: 36
new riboswitch yeppers: 37
new riboswitch yeppers: 38
new riboswitch yeppers: 39
new riboswitch yeppers: 40
new riboswitch yeppers: 41
new riboswitch yeppers: 42
new riboswitch yeppers: 43
new riboswitch yeppers: 44
new riboswitch yeppers: 45
new riboswitch yeppers: 46
new riboswitch yeppers: 47
new riboswitch yeppers: 48
new riboswitch yeppers: 49
new riboswitch yeppers: 50
new riboswitch yeppers: 51
new riboswitch yeppers: 52
new riboswitch yeppers: 53
new riboswitch yeppers: 54
new riboswitch yeppers: 55
new riboswitch yeppers: 56
new riboswitch yeppers: 57
new riboswitch yeppers: 58
new riboswitch yeppers: 59
new riboswitch yeppers: 60
new riboswitch yeppers: 61
new riboswitch yeppers: 62
new riboswitch yeppers: 63
new riboswitch yeppers: 64
new riboswitch yeppers: 65
new riboswitch yeppers: 66
new riboswitch yeppers: 67
new riboswitch yeppers: 68
new riboswitch yeppers: 69
new riboswitch yeppers: 70
new riboswitch yeppers: 71
new riboswitch yeppers: 72
new riboswitch yeppers: 73
new riboswitch yeppers: 74
new riboswitch yeppers: 75
new riboswitch yeppers: 76
new riboswitch yeppers: 77
new riboswitch yeppers: 78
new riboswitch yeppers: 79
new riboswitch yeppers: 80
new riboswitch yeppers: 81
new riboswitch yeppers: 82
new riboswitch yeppers: 83
new riboswitch yeppers: 84
new riboswitch yeppers: 85
new riboswitch yeppers: 86
new riboswitch yeppers: 87
new riboswitch yeppers: 88
new riboswitch yeppers: 89
new riboswitch yeppers: 90
new riboswitch yeppers: 91
new riboswitch yeppers: 92
new riboswitch yeppers: 93
new riboswitch yeppers: 94
new riboswitch yeppers: 95
new riboswitch yeppers: 96
new riboswitch yeppers: 97
new riboswitch yeppers: 98
new riboswitch yeppers: 99
new riboswitch yeppers: 100
new riboswitch yeppers: 101
new riboswitch yeppers: 102
new riboswitch yeppers: 103
new riboswitch yeppers: 104
new riboswitch yeppers: 105
new riboswitch yeppers: 106
new riboswitch yeppers: 107
new riboswitch yeppers: 108
new riboswitch yeppers: 109
new riboswitch yeppers: 110
new riboswitch yeppers: 111
new riboswitch yeppers: 112
new riboswitch yeppers: 113
new riboswitch yeppers: 114
new riboswitch yeppers: 115
new riboswitch yeppers: 116
new riboswitch yeppers: 117
new riboswitch yeppers: 118
new riboswitch yeppers: 119
new riboswitch yeppers: 120
new riboswitch yeppers: 121
new riboswitch yeppers: 122
new riboswitch yeppers: 123
new riboswitch yeppers: 124
new riboswitch yeppers: 125
new riboswitch yeppers: 126
new riboswitch yeppers: 127
new riboswitch yeppers: 128
new riboswitch yeppers: 129
new riboswitch yeppers: 130
new riboswitch yeppers: 131
new riboswitch yeppers: 132
new riboswitch yeppers: 133
new riboswitch yeppers: 134
new riboswitch yeppers: 135
new riboswitch yeppers: 136
new riboswitch yeppers: 137
new riboswitch yeppers: 138
new riboswitch yeppers: 139
new riboswitch yeppers: 140
new riboswitch yeppers: 141
new riboswitch yeppers: 142
new riboswitch yeppers: 143
new riboswitch yeppers: 144
new riboswitch yeppers: 145
new riboswitch yeppers: 146
new riboswitch yeppers: 147
new riboswitch yeppers: 148
new riboswitch yeppers: 149
new riboswitch yeppers: 150
new riboswitch yeppers: 151
new riboswitch yeppers: 152
new riboswitch yeppers: 153
new riboswitch yeppers: 154
new riboswitch yeppers: 155
new riboswitch yeppers: 156
new riboswitch yeppers: 157
new riboswitch yeppers: 158
new riboswitch yeppers: 159
new riboswitch yeppers: 160
new riboswitch yeppers: 161
new riboswitch yeppers: 162
new riboswitch yeppers: 163
new riboswitch yeppers: 164
new riboswitch yeppers: 165
new riboswitch yeppers: 166
new riboswitch yeppers: 167
new riboswitch yeppers: 168
new riboswitch yeppers: 169
new riboswitch yeppers: 170
new riboswitch yeppers: 171
new riboswitch yeppers: 172
new riboswitch yeppers: 173
new riboswitch yeppers: 174
new riboswitch yeppers: 175
new riboswitch yeppers: 176
new riboswitch yeppers: 177
new riboswitch yeppers: 178
new riboswitch yeppers: 179
new riboswitch yeppers: 180

,label,salt_molarity,temperature (Celsius),name_of_riboswitch_data,name_of_target_data,riboswitch_subcategory,switch_row,target_row,trigger_row,target_location,trigger_location,riboswitch_sequence,target_sequence,trigger_sequence,target_trigger_complex,reporter_sequence,complex_nucelotides,switch_structure,target_structure,reporter_structure,complex_structure,trigger_target_binding_percentage,switch_energy,target_energy,reporter_energy,complex_energy,switch_gc,switch_at,target_gc,target_at,reporter_gc,reporter_at,complex_gc,complex_at,switch_ensemble_defect,target_ensemble_defect,reporter_ensemble_defect,complex_ensemble_defect,switch_single_strandedness,target_single_strandedness,reporter_single_strandedness,complex_single_strandedness,trigger_single_strandedness,trigger_structure,switch_kmers,target_kmers,complex_kmers,rbs_validity,rbs_location,valid_loop,loop_sequence,loop_structure,loop_energy
0,1,0.1,25.0,Green Riboswitches,MS2 Virus,forward engineered 4,0,0,0,1761,1761,AAGAGUUGAACUUCUUUGUUGUCUUCGACAGGGUCUUAUCUUAUCU...,UGUCGAAGACAACAAAGAAGUUCAACUCUU,AAGAGUUGAACUUCUUUGUUGUCUUCGACA,UGUCGAAGACAACAAAGAAGUUCAACUCUUAAGAGUUGAACUUCUU...,ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGT...,UGUCGAAGACAACAAAGAAGUUCAACUCUUAAGAGUUGAACUUCUU...,.(((...((....((((((((....)))))))).....))...)))...,((((...))))...................,.......((..(((.((((((.......(((((...........((...,(((((((((((((((((((((((((((((())))))))))))))))...,1.0,-39.180000,-2.22,-297.820007,-90.570000,0.418605,0.581395,0.366667,0.633333,0.620253,0.379747,0.414201,0.585799,0.121307,0.288612,0.33967,0.070971,0.715622,0.741619,0.697854,0.656634,0.567852,.(((...((....((((((((....))))),"{'AAG': 2, 'AGA': 6, 'GAG': 4, 'AGU': 1, 'GUU'...","{'UGU': 1, 'GUC': 1, 'UCG': 1, 'CGA': 1, 'GAA'...","{'UGU': 3, 'GUC': 3, 'UCG': 3, 'CGA': 3, 'GAA'...",True,75.0,True,ACAGAAACAGAGGAGAU,((............).),0.0
1,1,0.1,25.0,Green Riboswitches,MS2 Virus,forward engineered 4,0,1,1,1762,1762,AAAGAGUUGAACUUCUUUGUUGUCUUCGACGGGUCUUAUCUUAUCU...,GUCGAAGACAACAAAGAAGUUCAACUCUUU,AAAGAGUUGAACUUCUUUGUUGUCUUCGAC,GUCGAAGACAACAAAGAAGUUCAACUCUUUAAAGAGUUGAACUUCU...,ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGT...,GUCGAAGACAACAAAGAAGUUCAACUCUUUAAAGAGUUGAACUUCU...,((((((......))))))((((((...((.(((......))).))....,(((...)))...(((((.((...))))))),.......((..(((.((((((.......(((((...........((...,(((((((((((((((((((((((((((((())))))))))))))))...,1.0,-36.759998,-2.55,-297.820007,-90.870003,0.418605,0.581395,0.366667,0.633333,0.620253,0.379747,0.414201,0.585799,0.219631,0.169816,0.33967,0.069966,0.710996,0.721629,0.697854,0.655846,0.610438,((((((......))))))((((((...((.,"{'AAA': 6, 'AAG': 2, 'AGA': 6, 'GAG': 4, 'AGU'...","{'GUC': 1, 'UCG': 1, 'CGA': 1, 'GAA': 2, 'AAG'...","{'GUC': 3, 'UCG': 3, 'CGA': 3, 'GAA': 5, 'AAG'...",True,75.0,True,ACAGAAACAGAGGAGAU,((............).),0.0
2,1,0.1,25.0,Green Riboswitches,MS2 Virus,forward engineered 4,0,2,2,1763,1763,UAAAGAGUUGAACUUCUUUGUUGUCUUCGAGGGUCUUAUCUUAUCU...,UCGAAGACAACAAAGAAGUUCAACUCUUUA,UAAAGAGUUGAACUUCUUUGUUGUCUUCGA,UCGAAGACAACAAAGAAGUUCAACUCUUUAUAAAGAGUUGAACUUC...,ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGT...,UCGAAGACAACAAAGAAGUUCAACUCUUUAUAAAGAGUUGAACUUC...,.((((((......))))))((((((.....((((...............,...........(((((.((...))))))).,.......((..(((.((((((.......(((((...........((...,(((((((((((((((((((((((((((((())))))))))))))))...,1.0,-37.310001,-1.86,-297.820007,-88.260002,0.410853,0.589147,0.333333,0.666667,0.620253,0.379747,0.402367,0.597633,0.123665,0.208042,0.33967,0.069328,0.705704,0.793337,0.697854,0.656291,0.582332,.((((((......))))))((((((.....,"{'UAA': 3, 'AAA': 6, 'AAG': 2, 'AGA': 6, 'GAG'...","{'UCG': 1, 'CGA': 1, 'GAA': 2, 'AAG': 3, 'AGA'...","{'UCG': 3, 'CGA': 3, 'GAA': 5, 'AAG': 5, 'AGA'...",True,75.0,True,ACAGAAACAGAGGAGAU,((............).),0.0
3,1,0.1,25.0,Green Riboswitches,MS2 Virus,forward engineered 4,0,3,3,1764,1764,AUAAAGAGUUGAACUUCUUUGUUGUCUUCGGGGUCUUAUCUUAUCU...,CGAAGACAACAAAGAAGUUCAACUCUUUAU,AUAAAGAGUUGAACUUCUUUGUUGUCUUCG,CGAAGACAACAAAGAAGUUCAACUCUUUAUAUAAAGAGUUGAACUU...,ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGT...,CGAAGACAACAAAGAAGUUCAACUCUUUAUAUAAAGAGUUGAACUU...,((((((((......))))))))((((.(((((.................,..........(((((.((...)))))))..,.......((..(((.((((((.......(((((...........((...,(((((((((((((((((((((((((((((())))))))))))))))...,1.0,-39.869999,-1.86,-297.820007,-88.029999,0.410853,0.589147,0.333333,0.666667,0.620253,0.379747,0.402367,0.597633,0.077246,0.207414,0.33967,0.068155,0.696882,0.793421,0.697854,0.655946,0.518079,((((((((......))))))))((((.(((,"{'AUA': 4, 'UAA': 3, 'AAA': 6, 'AAG': 2, 'AGA'...","{'CGA': 1, 'GAA': 2, 'AAG': 3, 'AGA': 2, 'GAC'...","{'CGA': 2, 'GAA': 5, 'AAG': 5, 'AGA': 8, 'GAC'...",True,75.0,True,ACAGAAACAGAGGAGAU,((............).),0.0
4,1,0.1,25.0,Green Riboswitches,MS2 Virus,forward engineered 4,0,4,4,1765,1765,CAUAAAGAGUUGAACUUCUUUGUUGUCUUCGGGUCUUAUCUUAUCU...,GAAGACAACAAAGAAGUUCAACUCUUUAUG,CAUAAAGAGUUGAACUUCUUUGUUGUCUUC,GAAGACAACAAAGAAGUUCAACUCUUUAUGCAUAAAGAGUUGAACU...,ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGT...,GAAGACAACAAAGAAGUUCAACUCUUUAUGCAUAAAGAGUUGAACU...,.((((((((......))))))))((((.((((((...............,.........(((((.((...)))))))...,.......((..(((.((((((.......(((((...........((...,(((((((((((((((((((((((((((((())))))))))))))))...,1.0,-42.980000,-1.86,-297.820007,-88.830002,0.410853,0.589147,0.333333,0.666667,0.620253,0.379747,0.402367,0.597633,0.040454,0.195940,0.33967,0.064349,0.688818,0.792237,0.697854,0.655820,0.536631,.((((((((......))))))))((((.((,"{'CAU': 2, 'AUA': 4, 'UAA': 3, 'AAA': 6, 'AAG'...","{'GAA': 2, 'AAG': 3, 'AGA': 2, 'GAC': 1, 'ACA'...","{'GAA': 5, 'AAG': 5, 'AGA': 8, 'GAC': 1, 'ACA'...",True,75.0,True,ACAGAAACAGAGGAGAU,((............).),0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
296473,1,0.1,25.0,Green Riboswitches,MS2 Virus,144 orthoganal first gen,180,1633,1633,3394,3394,CCCGUUUACGGGGGUCCCUCGGUCAGCUACGGGAGUAAAUGAAUAA...,GUAGCUGACCGAGGGACCCCCGUAAACGGG,CCCGUUUACGGGGGUCCCUCGGUCAGCUAC,GUAGCUGACCGAGGGACCCCCGUAAACGGGCCCGUUUACGGGGGUC...,ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGT...,GUAGCUGACCGAGGGACCCCCGUAAACGGGCCCGUUUACGGGGGUC...,((((....)))).(((((..(((((..(((....)))..)))...(...,((..((.....))..)).((((....)))),.......((..(((.((((((.......(((((...........((...,(((((((((((((((((((((((((((((())))))))))))))))...,1.0,-43.849998,-5.66,-297.820007,-108.900002,0.500000,0.500000,0.666667,0.333333,0.620253,0.379747,0.530864,0.469136,0.136851,0.251683,0.33967,0.055297,0.708205,0.788585,0.697854,0.679111,0.500266,((((....)))).(((((..(((((..(((,"{'CCC': 2, 'CCG': 1, 'CGU': 2, 'GUU': 1, 'UUU'...","{'GUA': 2, 'UAG': 1, 'AGC': 1, 'GCU': 1, 'CUG'...","{'GUA': 5, 'UAG': 2, 'AGC': 4, 'GCU': 3, 'CUG'...",True,68.0,False,N/A,N/A,N/A
296474,1,0.1,25.0,Green Riboswitches,MS2 Virus,144 orthoganal first gen,180,1634,1634,3395,3395,CCCCGUUUACGGGGGUCCCUCGGUCAGCUAGGGAGUAAAUGAAUAA...,UAGCUGACCGAGGGACCCCCGUAAACGGGG,CCCCGUUUACGGGGGUCCCUCGGUCAGCUA,UAGCUGACCGAGGGACCCCCGUAAACGGGGCCCCGUUUACGGGGGU...,ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGT...,UAGCUGACCGAGGGACCCCCGUAAACGGGGCCCCGUUUACGGGGGU...,(((((....)))))........(((.((((((.............(...,................(((((....))))),.......((..(((.((((((.......(((((...........((...,(((((((((((((((((((((((((((((())))))))))))))))...,1.0,-50.410000,-8.90,-297.820007,-108.440002,0.500000,0.500000,0.666667,0.333333,0.620253,0.379747,0.530864,0.469136,0.017910,0.068390,0.33967,0.057209,0.719823,0.804037,0.697854,0.679748,0.601954,(((((....)))))........(((.((((,"{'CCC': 3, 'CCG': 1, 'CGU': 2, 'GUU': 1, 'UUU'...","{'UAG': 1, 'AGC': 1, 'GCU': 1, 'CUG': 1, 'UGA'...","{'UAG': 3, 'AGC': 4, 'GCU': 3, 'CUG': 2, 'UGA'...",True,68.0,False,N/A,N/A,N/A
296475,1,0.1,25.0,Green Riboswitches,MS2 Virus,144 orthoganal first gen,180,1635,1635,3396,3396,ACCCCGUUUACGGGGGUCCCUCGGUCAGCUGGGAGUAAAUGAAUAA...,AGCUGACCGAGGGACCCCCGUAAACGGGGU,ACCCCGUUUACGGGGGUCCCUCGGUCAGCU,AGCUGACCGAGGGACCCCCGUAAACGGGGUACCCCGUUUACGGGGG...,ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGT...,AGCUGACCGAGGGACCCCCGUAAACGGGGUACCCCGUUUACGGGGG...,.(((((....)))))........(((.((((((............(...,...............(((((....))))).,.......((..(((.((((((.......(((((...........((...,(((((((((((((((((((((((((((((())))))))))))))))...,1.0,-48.369999,-9.71,-297.820007,-108.739998,0.500000,0.500000,0.666667,0.333333,0.620253,0.379747,0.530864,0.469136,0.030638,0.083266,0.33967,0.059628,0.719182,0.802805,0.697854,0.679567,0.635792,.(((((....)))))........(((.(((,"{'ACC': 3, 'CCC': 3, 'CCG': 1, 'CGU': 2, 'GUU'...","{'AGC': 1, 'GCU': 1, 'CUG': 1, 'UGA': 1, 'GAC'...","{'AGC': 4, 'GCU': 3, 'CUG': 3, 'UGA': 3, 'GAC'...",True,68.0,False,N/A,N/A,N/A
296476,1,0.1,25.0,Green Riboswitches,MS2 Virus,144 orthoganal first gen,180,1636,1636,3397,3397,CACCCCGUUUACGGGGGUCCCUCGGUCAGCGGGAGUAAAUGAAUAA...,GCUGACCGAGGGACCCCCGUAAACGGGGUG,CACCCCGUUUACGGGGGUCCCUCGGUCAGC,GCUGACCGAGGGACCCCCGUAAACGGGGUGCACCCCGUUUACGGGG...,ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGT...,GCUGACCGAGGGACCCCCGUAAACGGGGUGCACCCCGUUUACGGGG...,.((((((((..(((((...)))))...)))))).)).........(...,..............(((((....)))))..,.......((..(((.((((((.......(((((...........((...,(((((((((((((((((((((((((((((())))))))))))))))...,1.0,-47.380001,-9.71,-297.820007,-111.050003,0.508197,0.491803,0.700000,0.300000,0.620253,0.379747,0.543210,0.456790,0.108251,0.152778,0.33967,0.055352,0.724407,0.796578,0.697854,0.679115,0.600071,.((((((((..(((((...)))))...))),"{'CAC': 2, 'ACC': 3, 'CCC': 3, 'CCG': 1, 'CGU'...","{'GCU': 1, 'CUG': 1, 'UGA': 1, 'GAC': 2, 'ACC'...","{'GCU': 2, 'CUG': 2, 'UGA': 3, 'GAC': 4, 'ACC'...",True,68.0,False,N/A,N/A,N/A
296477,1,0.1,25.0,Green Riboswitches,MS2 Virus,144 orthoganal first gen,180,1637,1637,3398,3398,CCACCCCGUUUACGGGGGUCCCUCGGUCAGGGGAGUAAAUGAAUAA...,CUGACCGAGGGACCCCCGUAAACGGGGUGG,CCACCCCGUUUACGGGGGUCCCUCGGUCAG,CUGACCGAGGGACCCCCGUAAACGGGGUGGCCACCCCGUUUACGGG...,ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGT...,CUGACCGAGGGACCCCCGUAAACGGGGUGGCCACCCCGUUUACGGG...,...(((((....)))))......(.((((((..............(...,............((((((....))))).).,.......((..(((.((((((.......(((((...........((...,(((((((((((((((((((((((((((((())))))))))))))))...,1.0,-47.919998,-9.88,-297.820007,-110.430000,0.508197,0.491803,0.700000,0.300000,0.620253,0.379747,0.543210,0.456790,0.088592,0.140298,0.33967,0.054745,0.736824,0.786325,0.697854,0.679264,0.638836,...(((((....)))))......(.(((((,"{'CCA': 1, 'CAC': 2, 'ACC': 3, 'CCC': 3, 'CCG'...","{'CUG': 1, 'UGA': 1, 'GAC': 2, 'ACC': 2, 'CCG'...","{'CUG': 2, 'UGA': 3, 'GAC': 4, 'ACC': 5, 'CCG'...",True,68.0,False,N/A,N/A,N/A

new concetration now 1.0

,0,1,trigger_sequence
0,forward engineered 4,GGGUCUUAUCUUAUCUAUCUCGUUUAUCCCUGCAUACAGAAACAGA...,AAGAGUUGAACUUCUUUGUUGUCUUCGACA
1,forward engineered 4,GGGUCUUAUCUUAUCUAUCUCGUUUAUCCCUGCAUACAGAAACAGA...,AAAGAGUUGAACUUCUUUGUUGUCUUCGAC
2,forward engineered 4,GGGUCUUAUCUUAUCUAUCUCGUUUAUCCCUGCAUACAGAAACAGA...,UAAAGAGUUGAACUUCUUUGUUGUCUUCGA
3,forward engineered 4,GGGUCUUAUCUUAUCUAUCUCGUUUAUCCCUGCAUACAGAAACAGA...,AUAAAGAGUUGAACUUCUUUGUUGUCUUCG
4,forward engineered 4,GGGUCUUAUCUUAUCUAUCUCGUUUAUCCCUGCAUACAGAAACAGA...,CAUAAAGAGUUGAACUUCUUUGUUGUCUUC
...,...,...,...
296473,144 orthoganal first gen,GGGAGUAAAUGAAUAAGGUGAUAGAUGUGUAUGGACAGAGGAGACA...,CCCGUUUACGGGGGUCCCUCGGUCAGCUAC
296474,144 orthoganal first gen,GGGAGUAAAUGAAUAAGGUGAUAGAUGUGUAUGGACAGAGGAGACA...,CCCCGUUUACGGGGGUCCCUCGGUCAGCUA
296475,144 orthoganal first gen,GGGAGUAAAUGAAUAAGGUGAUAGAUGUGUAUGGACAGAGGAGACA...,ACCCCGUUUACGGGGGUCCCUCGGUCAGCU
296476,144 orthoganal first gen,GGGAGUAAAUGAAUAAGGUGAUAGAUGUGUAUGGACAGAGGAGACA...,CACCCCGUUUACGGGGGUCCCUCGGUCAGC
296477,144 orthoganal first gen,GGGAGUAAAUGAAUAAGGUGAUAGAUGUGUAUGGACAGAGGAGACA...,CCACCCCGUUUACGGGGGUCCCUCGGUCAG

We are starting: 0.0
We are starting: 1.0
We are starting: 2.0
preliminary data done and dusted
Reporter row data is: ['.......((..(((.((((((.......(((((.((......))((((((((.(((((.(.....).))))).))...)))))))))))(((........))).(((((((((((.(((((((((.......(((((((((.(......))))..)))).))..))))))))).).)))).))))))((((((...)))))).....((((((((.((((....)))))))))))).((((.(((((.(.(((.(((((((((((((((.((.......)).))))))))))))......((.....)).))).))).).))))).)))).((........)).)))))))))))...(((((..((((((......((((..((...))..)))).......(((((..((((((.((....(....)...))...)))))))))))...((((.(.(((..((((((((((((...(((((((...((((.((.....(((..((((...(((..(((.(((((..........))))).(((....))).)))....))).....))))..)))..))))))))))))).....((((((.....))).)))....((((.......))))......)).))).))....)))))..))).).))))((((((........))))))))))))..)))))........', -341.07000732421875, 0.620253164556962, 0.379746835443038, 0.37567186213465853, 0.6926941478000694]
new riboswitch yeppers: 0
new riboswitch yeppers: 1
new riboswitch yeppers: 2
new riboswitch yeppers: 3
new riboswitch yeppers: 4
new riboswitch yeppers: 5
new riboswitch yeppers: 6
new riboswitch yeppers: 7
new riboswitch yeppers: 8
new riboswitch yeppers: 9
new riboswitch yeppers: 10
new riboswitch yeppers: 11
new riboswitch yeppers: 12
new riboswitch yeppers: 13
new riboswitch yeppers: 14
new riboswitch yeppers: 15
new riboswitch yeppers: 16
new riboswitch yeppers: 17
new riboswitch yeppers: 18
new riboswitch yeppers: 19
new riboswitch yeppers: 20
new riboswitch yeppers: 21
new riboswitch yeppers: 22
new riboswitch yeppers: 23
new riboswitch yeppers: 24
new riboswitch yeppers: 25
new riboswitch yeppers: 26
new riboswitch yeppers: 27
new riboswitch yeppers: 28
new riboswitch yeppers: 29
new riboswitch yeppers: 30
new riboswitch yeppers: 31
new riboswitch yeppers: 32
new riboswitch yeppers: 33
new riboswitch yeppers: 34
new riboswitch yeppers: 35
new riboswitch yeppers: 36
new riboswitch yeppers: 37
new riboswitch yeppers: 38
new riboswitch yeppers: 39
new riboswitch yeppers: 40
new riboswitch yeppers: 41
new riboswitch yeppers: 42
new riboswitch yeppers: 43
new riboswitch yeppers: 44
new riboswitch yeppers: 45
new riboswitch yeppers: 46
new riboswitch yeppers: 47
new riboswitch yeppers: 48
new riboswitch yeppers: 49
new riboswitch yeppers: 50
new riboswitch yeppers: 51
new riboswitch yeppers: 52
new riboswitch yeppers: 53
new riboswitch yeppers: 54
new riboswitch yeppers: 55
new riboswitch yeppers: 56
new riboswitch yeppers: 57
new riboswitch yeppers: 58
new riboswitch yeppers: 59
new riboswitch yeppers: 60
new riboswitch yeppers: 61
new riboswitch yeppers: 62
new riboswitch yeppers: 63
new riboswitch yeppers: 64
new riboswitch yeppers: 65
new riboswitch yeppers: 66
new riboswitch yeppers: 67
new riboswitch yeppers: 68
new riboswitch yeppers: 69
new riboswitch yeppers: 70
new riboswitch yeppers: 71
new riboswitch yeppers: 72
new riboswitch yeppers: 73
new riboswitch yeppers: 74
new riboswitch yeppers: 75
new riboswitch yeppers: 76
new riboswitch yeppers: 77
new riboswitch yeppers: 78
new riboswitch yeppers: 79
new riboswitch yeppers: 80
new riboswitch yeppers: 81
new riboswitch yeppers: 82
new riboswitch yeppers: 83
new riboswitch yeppers: 84
new riboswitch yeppers: 85
new riboswitch yeppers: 86
new riboswitch yeppers: 87
new riboswitch yeppers: 88
new riboswitch yeppers: 89
new riboswitch yeppers: 90
new riboswitch yeppers: 91
new riboswitch yeppers: 92
new riboswitch yeppers: 93
new riboswitch yeppers: 94
new riboswitch yeppers: 95
new riboswitch yeppers: 96
new riboswitch yeppers: 97
new riboswitch yeppers: 98
new riboswitch yeppers: 99
new riboswitch yeppers: 100
new riboswitch yeppers: 101
new riboswitch yeppers: 102
new riboswitch yeppers: 103
new riboswitch yeppers: 104
new riboswitch yeppers: 105
new riboswitch yeppers: 106
new riboswitch yeppers: 107
new riboswitch yeppers: 108
new riboswitch yeppers: 109
new riboswitch yeppers: 110
new riboswitch yeppers: 111
new riboswitch yeppers: 112
new riboswitch yeppers: 113
new riboswitch yeppers: 114
new riboswitch yeppers: 115
new riboswitch yeppers: 116
new riboswitch yeppers: 117
new riboswitch yeppers: 118
new riboswitch yeppers: 119
new riboswitch yeppers: 120
new riboswitch yeppers: 121
new riboswitch yeppers: 122
new riboswitch yeppers: 123
new riboswitch yeppers: 124
new riboswitch yeppers: 125
new riboswitch yeppers: 126
new riboswitch yeppers: 127
new riboswitch yeppers: 128
new riboswitch yeppers: 129
new riboswitch yeppers: 130
new riboswitch yeppers: 131
new riboswitch yeppers: 132
new riboswitch yeppers: 133
new riboswitch yeppers: 134
new riboswitch yeppers: 135
new riboswitch yeppers: 136
new riboswitch yeppers: 137
new riboswitch yeppers: 138
new riboswitch yeppers: 139
new riboswitch yeppers: 140
new riboswitch yeppers: 141
new riboswitch yeppers: 142
new riboswitch yeppers: 143
new riboswitch yeppers: 144
new riboswitch yeppers: 145
new riboswitch yeppers: 146
new riboswitch yeppers: 147
new riboswitch yeppers: 148
new riboswitch yeppers: 149
new riboswitch yeppers: 150
new riboswitch yeppers: 151
new riboswitch yeppers: 152
new riboswitch yeppers: 153
new riboswitch yeppers: 154
new riboswitch yeppers: 155
new riboswitch yeppers: 156
new riboswitch yeppers: 157
new riboswitch yeppers: 158
new riboswitch yeppers: 159
new riboswitch yeppers: 160
new riboswitch yeppers: 161
new riboswitch yeppers: 162
new riboswitch yeppers: 163
new riboswitch yeppers: 164
new riboswitch yeppers: 165
new riboswitch yeppers: 166
new riboswitch yeppers: 167
new riboswitch yeppers: 168
new riboswitch yeppers: 169
new riboswitch yeppers: 170
new riboswitch yeppers: 171
new riboswitch yeppers: 172
new riboswitch yeppers: 173
new riboswitch yeppers: 174
new riboswitch yeppers: 175
new riboswitch yeppers: 176
new riboswitch yeppers: 177
new riboswitch yeppers: 178
new riboswitch yeppers: 179
new riboswitch yeppers: 180

,label,salt_molarity,temperature (Celsius),name_of_riboswitch_data,name_of_target_data,riboswitch_subcategory,switch_row,target_row,trigger_row,target_location,trigger_location,riboswitch_sequence,target_sequence,trigger_sequence,target_trigger_complex,reporter_sequence,complex_nucelotides,switch_structure,target_structure,reporter_structure,complex_structure,trigger_target_binding_percentage,switch_energy,target_energy,reporter_energy,complex_energy,switch_gc,switch_at,target_gc,target_at,reporter_gc,reporter_at,complex_gc,complex_at,switch_ensemble_defect,target_ensemble_defect,reporter_ensemble_defect,complex_ensemble_defect,switch_single_strandedness,target_single_strandedness,reporter_single_strandedness,complex_single_strandedness,trigger_single_strandedness,trigger_structure,switch_kmers,target_kmers,complex_kmers,rbs_validity,rbs_location,valid_loop,loop_sequence,loop_structure,loop_energy
0,1,1.0,25.0,Green Riboswitches,MS2 Virus,forward engineered 4,0,0,0,1761,1761,AAGAGUUGAACUUCUUUGUUGUCUUCGACAGGGUCUUAUCUUAUCU...,UGUCGAAGACAACAAAGAAGUUCAACUCUU,AAGAGUUGAACUUCUUUGUUGUCUUCGACA,UGUCGAAGACAACAAAGAAGUUCAACUCUUAAGAGUUGAACUUCUU...,ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGT...,UGUCGAAGACAACAAAGAAGUUCAACUCUUAAGAGUUGAACUUCUU...,.(((...((....((((((((....)))))))).....))...)))...,((((...))))...((((........)))),.......((..(((.((((((.......(((((.((......))((...,(((((((((((((((((((((((((((((())))))))))))))))...,1.0,-46.529999,-3.85,-341.070007,-99.010002,0.418605,0.581395,0.366667,0.633333,0.620253,0.379747,0.414201,0.585799,0.103846,0.189347,0.375672,0.064998,0.709686,0.720878,0.692694,0.652639,0.558371,.(((...((....((((((((....))))),"{'AAG': 2, 'AGA': 6, 'GAG': 4, 'AGU': 1, 'GUU'...","{'UGU': 1, 'GUC': 1, 'UCG': 1, 'CGA': 1, 'GAA'...","{'UGU': 3, 'GUC': 3, 'UCG': 3, 'CGA': 3, 'GAA'...",True,75.0,True,ACAGAAACAGAGGAGAU,((............).),0.0
1,1,1.0,25.0,Green Riboswitches,MS2 Virus,forward engineered 4,0,1,1,1762,1762,AAAGAGUUGAACUUCUUUGUUGUCUUCGACGGGUCUUAUCUUAUCU...,GUCGAAGACAACAAAGAAGUUCAACUCUUU,AAAGAGUUGAACUUCUUUGUUGUCUUCGAC,GUCGAAGACAACAAAGAAGUUCAACUCUUUAAAGAGUUGAACUUCU...,ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGT...,GUCGAAGACAACAAAGAAGUUCAACUCUUUAAAGAGUUGAACUUCU...,((((((......))))))((((((...((.(((......))).))....,(((...)))...(((((........))))),.......((..(((.((((((.......(((((.((......))((...,(((((((((((((((((((((((((((((())))))))))))))))...,1.0,-44.080002,-4.18,-341.070007,-99.309998,0.418605,0.581395,0.366667,0.633333,0.620253,0.379747,0.414201,0.585799,0.193439,0.188260,0.375672,0.064390,0.705650,0.714181,0.692694,0.651927,0.589602,((((((......))))))((((((...((.,"{'AAA': 6, 'AAG': 2, 'AGA': 6, 'GAG': 4, 'AGU'...","{'GUC': 1, 'UCG': 1, 'CGA': 1, 'GAA': 2, 'AAG'...","{'GUC': 3, 'UCG': 3, 'CGA': 3, 'GAA': 5, 'AAG'...",True,75.0,True,ACAGAAACAGAGGAGAU,((............).),0.0
2,1,1.0,25.0,Green Riboswitches,MS2 Virus,forward engineered 4,0,2,2,1763,1763,UAAAGAGUUGAACUUCUUUGUUGUCUUCGAGGGUCUUAUCUUAUCU...,UCGAAGACAACAAAGAAGUUCAACUCUUUA,UAAAGAGUUGAACUUCUUUGUUGUCUUCGA,UCGAAGACAACAAAGAAGUUCAACUCUUUAUAAAGAGUUGAACUUC...,ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGT...,UCGAAGACAACAAAGAAGUUCAACUCUUUAUAAAGAGUUGAACUUC...,.((((((......))))))((((((.....((((...............,..(((((.(((......)))....))))).,.......((..(((.((((((.......(((((.((......))((...,(((((((((((((((((((((((((((((())))))))))))))))...,1.0,-44.279999,-3.37,-341.070007,-96.699997,0.410853,0.589147,0.333333,0.666667,0.620253,0.379747,0.402367,0.597633,0.128074,0.458797,0.375672,0.063392,0.703733,0.777858,0.692694,0.652316,0.579634,.((((((......))))))((((((.....,"{'UAA': 3, 'AAA': 6, 'AAG': 2, 'AGA': 6, 'GAG'...","{'UCG': 1, 'CGA': 1, 'GAA': 2, 'AAG': 3, 'AGA'...","{'UCG': 3, 'CGA': 3, 'GAA': 5, 'AAG': 5, 'AGA'...",True,75.0,True,ACAGAAACAGAGGAGAU,((............).),0.0
3,1,1.0,25.0,Green Riboswitches,MS2 Virus,forward engineered 4,0,3,3,1764,1764,AUAAAGAGUUGAACUUCUUUGUUGUCUUCGGGGUCUUAUCUUAUCU...,CGAAGACAACAAAGAAGUUCAACUCUUUAU,AUAAAGAGUUGAACUUCUUUGUUGUCUUCG,CGAAGACAACAAAGAAGUUCAACUCUUUAUAUAAAGAGUUGAACUU...,ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGT...,CGAAGACAACAAAGAAGUUCAACUCUUUAUAUAAAGAGUUGAACUU...,((((((((......))))))))((((.(((((.................,.(((((.(((......)))....)))))..,.......((..(((.((((((.......(((((.((......))((...,(((((((((((((((((((((((((((((())))))))))))))))...,1.0,-46.520000,-3.37,-341.070007,-96.470001,0.410853,0.589147,0.333333,0.666667,0.620253,0.379747,0.402367,0.597633,0.119461,0.458171,0.375672,0.063516,0.692190,0.778078,0.692694,0.652045,0.522921,((((((((......))))))))((((.(((,"{'AUA': 4, 'UAA': 3, 'AAA': 6, 'AAG': 2, 'AGA'...","{'CGA': 1, 'GAA': 2, 'AAG': 3, 'AGA': 2, 'GAC'...","{'CGA': 2, 'GAA': 5, 'AAG': 5, 'AGA': 8, 'GAC'...",True,75.0,True,ACAGAAACAGAGGAGAU,((............).),0.0
4,1,1.0,25.0,Green Riboswitches,MS2 Virus,forward engineered 4,0,4,4,1765,1765,CAUAAAGAGUUGAACUUCUUUGUUGUCUUCGGGUCUUAUCUUAUCU...,GAAGACAACAAAGAAGUUCAACUCUUUAUG,CAUAAAGAGUUGAACUUCUUUGUUGUCUUC,GAAGACAACAAAGAAGUUCAACUCUUUAUGCAUAAAGAGUUGAACU...,ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGT...,GAAGACAACAAAGAAGUUCAACUCUUUAUGCAUAAAGAGUUGAACU...,.((((((((......))))))))((((.((((((...............,(((((.(((......)))....)))))...,.......((..(((.((((((.......(((((.((......))((...,(((((((((((((((((((((((((((((())))))))))))))))...,1.0,-49.700001,-3.25,-341.070007,-97.269997,0.410853,0.589147,0.333333,0.666667,0.620253,0.379747,0.402367,0.597633,0.038462,0.520330,0.375672,0.059097,0.687868,0.777629,0.692694,0.651910,0.537972,.((((((((......))))))))((((.((,"{'CAU': 2, 'AUA': 4, 'UAA': 3, 'AAA': 6, 'AAG'...","{'GAA': 2, 'AAG': 3, 'AGA': 2, 'GAC': 1, 'ACA'...","{'GAA': 5, 'AAG': 5, 'AGA': 8, 'GAC': 1, 'ACA'...",True,75.0,True,ACAGAAACAGAGGAGAU,((............).),0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
296473,1,1.0,25.0,Green Riboswitches,MS2 Virus,144 orthoganal first gen,180,1633,1633,3394,3394,CCCGUUUACGGGGGUCCCUCGGUCAGCUACGGGAGUAAAUGAAUAA...,GUAGCUGACCGAGGGACCCCCGUAAACGGG,CCCGUUUACGGGGGUCCCUCGGUCAGCUAC,GUAGCUGACCGAGGGACCCCCGUAAACGGGCCCGUUUACGGGGGUC...,ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGT...,GUAGCUGACCGAGGGACCCCCGUAAACGGGCCCGUUUACGGGGGUC...,((((....)))).(((((..(((((..(((....)))..)))...(...,((..((.....))..)).((((....)))),.......((..(((.((((((.......(((((.((......))((...,(((((((((((((((((((((((((((((())))))))))))))))...,1.0,-51.580002,-7.98,-341.070007,-116.470001,0.500000,0.500000,0.666667,0.333333,0.620253,0.379747,0.530864,0.469136,0.062159,0.129106,0.375672,0.066760,0.697579,0.753355,0.692694,0.672812,0.449380,((((....)))).(((((..(((((..(((,"{'CCC': 2, 'CCG': 1, 'CGU': 2, 'GUU': 1, 'UUU'...","{'GUA': 2, 'UAG': 1, 'AGC': 1, 'GCU': 1, 'CUG'...","{'GUA': 5, 'UAG': 2, 'AGC': 4, 'GCU': 3, 'CUG'...",True,68.0,False,N/A,N/A,N/A
296474,1,1.0,25.0,Green Riboswitches,MS2 Virus,144 orthoganal first gen,180,1634,1634,3395,3395,CCCCGUUUACGGGGGUCCCUCGGUCAGCUAGGGAGUAAAUGAAUAA...,UAGCUGACCGAGGGACCCCCGUAAACGGGG,CCCCGUUUACGGGGGUCCCUCGGUCAGCUA,UAGCUGACCGAGGGACCCCCGUAAACGGGGCCCCGUUUACGGGGGU...,ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGT...,UAGCUGACCGAGGGACCCCCGUAAACGGGGCCCCGUUUACGGGGGU...,(((((....)))))........(((.((((((.............(...,...((.....))....(((((....))))),.......((..(((.((((((.......(((((.((......))((...,(((((((((((((((((((((((((((((())))))))))))))))...,1.0,-56.299999,-9.74,-341.070007,-116.010002,0.500000,0.500000,0.666667,0.333333,0.620253,0.379747,0.530864,0.469136,0.026077,0.151723,0.375672,0.068870,0.718246,0.783586,0.692694,0.674069,0.600732,(((((....)))))........(((.((((,"{'CCC': 3, 'CCG': 1, 'CGU': 2, 'GUU': 1, 'UUU'...","{'UAG': 1, 'AGC': 1, 'GCU': 1, 'CUG': 1, 'UGA'...","{'UAG': 3, 'AGC': 4, 'GCU': 3, 'CUG': 2, 'UGA'...",True,68.0,False,N/A,N/A,N/A
296475,1,1.0,25.0,Green Riboswitches,MS2 Virus,144 orthoganal first gen,180,1635,1635,3396,3396,ACCCCGUUUACGGGGGUCCCUCGGUCAGCUGGGAGUAAAUGAAUAA...,AGCUGACCGAGGGACCCCCGUAAACGGGGU,ACCCCGUUUACGGGGGUCCCUCGGUCAGCU,AGCUGACCGAGGGACCCCCGUAAACGGGGUACCCCGUUUACGGGGG...,ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGT...,AGCUGACCGAGGGACCCCCGUAAACGGGGUACCCCGUUUACGGGGG...,.(((((....)))))........(((.((((((............(...,..((.....))....(((((....))))).,.......((..(((.((((((.......(((((.((......))((...,(((((((((((((((((((((((((((((())))))))))))))))...,1.0,-54.270000,-10.55,-341.070007,-116.309998,0.500000,0.500000,0.666667,0.333333,0.620253,0.379747,0.530864,0.469136,0.046032,0.175548,0.375672,0.071386,0.716120,0.782657,0.692694,0.673208,0.631996,.(((((....)))))........(((.(((,"{'ACC': 3, 'CCC': 3, 'CCG': 1, 'CGU': 2, 'GUU'...","{'AGC': 1, 'GCU': 1, 'CUG': 1, 'UGA': 1, 'GAC'...","{'AGC': 4, 'GCU': 3, 'CUG': 3, 'UGA': 3, 'GAC'...",True,68.0,False,N/A,N/A,N/A
296476,1,1.0,25.0,Green Riboswitches,MS2 Virus,144 orthoganal first gen,180,1636,1636,3397,3397,CACCCCGUUUACGGGGGUCCCUCGGUCAGCGGGAGUAAAUGAAUAA...,GCUGACCGAGGGACCCCCGUAAACGGGGUG,CACCCCGUUUACGGGGGUCCCUCGGUCAGC,GCUGACCGAGGGACCCCCGUAAACGGGGUGCACCCCGUUUACGGGG...,ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGT...,GCUGACCGAGGGACCCCCGUAAACGGGGUGCACCCCGUUUACGGGG...,.((((((((..(((((...)))))...)))))).)).........(...,.((.....))....(((((....)))))..,.......((..(((.((((((.......(((((.((......))((...,(((((((((((((((((((((((((((((())))))))))))))))...,1.0,-53.590000,-10.55,-341.070007,-118.620003,0.508197,0.491803,0.700000,0.300000,0.620253,0.379747,0.543210,0.456790,0.133451,0.257925,0.375672,0.066686,0.720316,0.775283,0.692694,0.672834,0.598615,.((((((((..(((((...)))))...))),"{'CAC': 2, 'ACC': 3, 'CCC': 3, 'CCG': 1, 'CGU'...","{'GCU': 1, 'CUG': 1, 'UGA': 1, 'GAC': 2, 'ACC'...","{'GCU': 2, 'CUG': 2, 'UGA': 3, 'GAC': 4, 'ACC'...",True,68.0,False,N/A,N/A,N/A
296477,1,1.0,25.0,Green Riboswitches,MS2 Virus,144 orthoganal first gen,180,1637,1637,3398,3398,CCACCCCGUUUACGGGGGUCCCUCGGUCAGGGGAGUAAAUGAAUAA...,CUGACCGAGGGACCCCCGUAAACGGGGUGG,CCACCCCGUUUACGGGGGUCCCUCGGUCAG,CUGACCGAGGGACCCCCGUAAACGGGGUGGCCACCCCGUUUACGGG...,ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGT...,CUGACCGAGGGACCCCCGUAAACGGGGUGGCCACCCCGUUUACGGG...,...(((((....)))))......(.((((((..............(...,............((((((....))))).).,.......((..(((.((((((.......(((((.((......))((...,(((((((((((((((((((((((((((((())))))))))))))))...,1.0,-53.869999,-10.99,-341.070007,-118.000000,0.508197,0.491803,0.700000,0.300000,0.620253,0.379747,0.543210,0.456790,0.098313,0.179838,0.375672,0.063579,0.731871,0.764807,0.692694,0.673467,0.624758,...(((((....)))))......(.(((((,"{'CCA': 1, 'CAC': 2, 'ACC': 3, 'CCC': 3, 'CCG'...","{'CUG': 1, 'UGA': 1, 'GAC': 2, 'ACC': 2, 'CCG'...","{'CUG': 2, 'UGA': 3, 'GAC': 4, 'ACC': 5, 'CCG'...",True,68.0,False,N/A,N/A,N/A

,label,salt_molarity,temperature (Celsius),name_of_riboswitch_data,name_of_target_data,riboswitch_subcategory,switch_row,trigger_row,target_row,target_location,trigger_location,riboswitch_sequence,trigger_sequence,target_sequence,target_trigger_complex,reporter_sequence,switch_structure,target_structure,switch_energy,target_energy,trigger_single_strandedness,trigger_structure,switch_kmers,target_kmers,rbs_validity,rbs_location,valid_loop,loop_sequence,loop_structure,loop_energy,complex_nucelotides,complex_structure,complex_energy,complex_gc,complex_at,switch_gc,switch_at,target_gc,target_at,switch_ensemble_defect,target_ensemble_defect,complex_ensemble_defect,switch_single_strandedness,target_single_strandedness,complex_single_strandedness,complex_kmers,reporter_structure,reporter_energy,reporter_gc,reporter_at,reporter_ensemble_defect,reporter_single_strandedness,trigger_target_binding_percentage
0,1,0.1,25.0,Green Riboswitches,MS2 Virus,forward engineered 4,0,0,0,1761,1761,AAGAGUUGAACUUCUUUGUUGUCUUCGACAGGGUCUUAUCUUAUCU...,AAGAGUUGAACUUCUUUGUUGUCUUCGACA,UGUCGAAGACAACAAAGAAGUUCAACUCUU,UGUCGAAGACAACAAAGAAGUUCAACUCUUAAGAGUUGAACUUCUU...,ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGT...,.(((...((....((((((((....)))))))).....))...)))...,((((...))))...................,-39.180000,-2.22,0.567852,.(((...((....((((((((....))))),"{'AAG': 2, 'AGA': 6, 'GAG': 4, 'AGU': 1, 'GUU'...","{'UGU': 1, 'GUC': 1, 'UCG': 1, 'CGA': 1, 'GAA'...",True,75.0,True,ACAGAAACAGAGGAGAU,((............).),0.0,UGUCGAAGACAACAAAGAAGUUCAACUCUUAAGAGUUGAACUUCUU...,(((((((((((((((((((((((((((((())))))))))))))))...,-90.570000,0.414201,0.585799,0.418605,0.581395,0.366667,0.633333,0.121307,0.288612,0.070971,0.715622,0.741619,0.656634,"{'UGU': 3, 'GUC': 3, 'UCG': 3, 'CGA': 3, 'GAA'...",.......((..(((.((((((.......(((((...........((...,-297.820007,0.620253,0.379747,0.339670,0.697854,1.0
1,1,0.1,25.0,Green Riboswitches,MS2 Virus,forward engineered 4,0,1,1,1762,1762,AAAGAGUUGAACUUCUUUGUUGUCUUCGACGGGUCUUAUCUUAUCU...,AAAGAGUUGAACUUCUUUGUUGUCUUCGAC,GUCGAAGACAACAAAGAAGUUCAACUCUUU,GUCGAAGACAACAAAGAAGUUCAACUCUUUAAAGAGUUGAACUUCU...,ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGT...,((((((......))))))((((((...((.(((......))).))....,(((...)))...(((((.((...))))))),-36.759998,-2.55,0.610438,((((((......))))))((((((...((.,"{'AAA': 6, 'AAG': 2, 'AGA': 6, 'GAG': 4, 'AGU'...","{'GUC': 1, 'UCG': 1, 'CGA': 1, 'GAA': 2, 'AAG'...",True,75.0,True,ACAGAAACAGAGGAGAU,((............).),0.0,GUCGAAGACAACAAAGAAGUUCAACUCUUUAAAGAGUUGAACUUCU...,(((((((((((((((((((((((((((((())))))))))))))))...,-90.870003,0.414201,0.585799,0.418605,0.581395,0.366667,0.633333,0.219631,0.169816,0.069966,0.710996,0.721629,0.655846,"{'GUC': 3, 'UCG': 3, 'CGA': 3, 'GAA': 5, 'AAG'...",.......((..(((.((((((.......(((((...........((...,-297.820007,0.620253,0.379747,0.339670,0.697854,1.0
2,1,0.1,25.0,Green Riboswitches,MS2 Virus,forward engineered 4,0,2,2,1763,1763,UAAAGAGUUGAACUUCUUUGUUGUCUUCGAGGGUCUUAUCUUAUCU...,UAAAGAGUUGAACUUCUUUGUUGUCUUCGA,UCGAAGACAACAAAGAAGUUCAACUCUUUA,UCGAAGACAACAAAGAAGUUCAACUCUUUAUAAAGAGUUGAACUUC...,ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGT...,.((((((......))))))((((((.....((((...............,...........(((((.((...))))))).,-37.310001,-1.86,0.582332,.((((((......))))))((((((.....,"{'UAA': 3, 'AAA': 6, 'AAG': 2, 'AGA': 6, 'GAG'...","{'UCG': 1, 'CGA': 1, 'GAA': 2, 'AAG': 3, 'AGA'...",True,75.0,True,ACAGAAACAGAGGAGAU,((............).),0.0,UCGAAGACAACAAAGAAGUUCAACUCUUUAUAAAGAGUUGAACUUC...,(((((((((((((((((((((((((((((())))))))))))))))...,-88.260002,0.402367,0.597633,0.410853,0.589147,0.333333,0.666667,0.123665,0.208042,0.069328,0.705704,0.793337,0.656291,"{'UCG': 3, 'CGA': 3, 'GAA': 5, 'AAG': 5, 'AGA'...",.......((..(((.((((((.......(((((...........((...,-297.820007,0.620253,0.379747,0.339670,0.697854,1.0
3,1,0.1,25.0,Green Riboswitches,MS2 Virus,forward engineered 4,0,3,3,1764,1764,AUAAAGAGUUGAACUUCUUUGUUGUCUUCGGGGUCUUAUCUUAUCU...,AUAAAGAGUUGAACUUCUUUGUUGUCUUCG,CGAAGACAACAAAGAAGUUCAACUCUUUAU,CGAAGACAACAAAGAAGUUCAACUCUUUAUAUAAAGAGUUGAACUU...,ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGT...,((((((((......))))))))((((.(((((.................,..........(((((.((...)))))))..,-39.869999,-1.86,0.518079,((((((((......))))))))((((.(((,"{'AUA': 4, 'UAA': 3, 'AAA': 6, 'AAG': 2, 'AGA'...","{'CGA': 1, 'GAA': 2, 'AAG': 3, 'AGA': 2, 'GAC'...",True,75.0,True,ACAGAAACAGAGGAGAU,((............).),0.0,CGAAGACAACAAAGAAGUUCAACUCUUUAUAUAAAGAGUUGAACUU...,(((((((((((((((((((((((((((((())))))))))))))))...,-88.029999,0.402367,0.597633,0.410853,0.589147,0.333333,0.666667,0.077246,0.207414,0.068155,0.696882,0.793421,0.655946,"{'CGA': 2, 'GAA': 5, 'AAG': 5, 'AGA': 8, 'GAC'...",.......((..(((.((((((.......(((((...........((...,-297.820007,0.620253,0.379747,0.339670,0.697854,1.0
4,1,0.1,25.0,Green Riboswitches,MS2 Virus,forward engineered 4,0,4,4,1765,1765,CAUAAAGAGUUGAACUUCUUUGUUGUCUUCGGGUCUUAUCUUAUCU...,CAUAAAGAGUUGAACUUCUUUGUUGUCUUC,GAAGACAACAAAGAAGUUCAACUCUUUAUG,GAAGACAACAAAGAAGUUCAACUCUUUAUGCAUAAAGAGUUGAACU...,ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGT...,.((((((((......))))))))((((.((((((...............,.........(((((.((...)))))))...,-42.980000,-1.86,0.536631,.((((((((......))))))))((((.((,"{'CAU': 2, 'AUA': 4, 'UAA': 3, 'AAA': 6, 'AAG'...","{'GAA': 2, 'AAG': 3, 'AGA': 2, 'GAC': 1, 'ACA'...",True,75.0,True,ACAGAAACAGAGGAGAU,((............).),0.0,GAAGACAACAAAGAAGUUCAACUCUUUAUGCAUAAAGAGUUGAACU...,(((((((((((((((((((((((((((((())))))))))))))))...,-88.830002,0.402367,0.597633,0.410853,0.589147,0.333333,0.666667,0.040454,0.195940,0.064349,0.688818,0.792237,0.655820,"{'GAA': 5, 'AAG': 5, 'AGA': 8, 'GAC': 1, 'ACA'...",.......((..(((.((((((.......(((((...........((...,-297.820007,0.620253,0.379747,0.339670,0.697854,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
592951,1,1.0,25.0,Green Riboswitches,MS2 Virus,144 orthoganal first gen,180,1633,1633,3394,3394,CCCGUUUACGGGGGUCCCUCGGUCAGCUACGGGAGUAAAUGAAUAA...,CCCGUUUACGGGGGUCCCUCGGUCAGCUAC,GUAGCUGACCGAGGGACCCCCGUAAACGGG,GUAGCUGACCGAGGGACCCCCGUAAACGGGCCCGUUUACGGGGGUC...,ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGT...,((((....)))).(((((..(((((..(((....)))..)))...(...,((..((.....))..)).((((....)))),-51.580002,-7.98,0.449380,((((....)))).(((((..(((((..(((,"{'CCC': 2, 'CCG': 1, 'CGU': 2, 'GUU': 1, 'UUU'...","{'GUA': 2, 'UAG': 1, 'AGC': 1, 'GCU': 1, 'CUG'...",True,68.0,False,N/A,N/A,N/A,GUAGCUGACCGAGGGACCCCCGUAAACGGGCCCGUUUACGGGGGUC...,(((((((((((((((((((((((((((((())))))))))))))))...,-116.470001,0.530864,0.469136,0.500000,0.500000,0.666667,0.333333,0.062159,0.129106,0.066760,0.697579,0.753355,0.672812,"{'GUA': 5, 'UAG': 2, 'AGC': 4, 'GCU': 3, 'CUG'...",.......((..(((.((((((.......(((((.((......))((...,-341.070007,0.620253,0.379747,0.375672,0.692694,1.0
592952,1,1.0,25.0,Green Riboswitches,MS2 Virus,144 orthoganal first gen,180,1634,1634,3395,3395,CCCCGUUUACGGGGGUCCCUCGGUCAGCUAGGGAGUAAAUGAAUAA...,CCCCGUUUACGGGGGUCCCUCGGUCAGCUA,UAGCUGACCGAGGGACCCCCGUAAACGGGG,UAGCUGACCGAGGGACCCCCGUAAACGGGGCCCCGUUUACGGGGGU...,ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGT...,(((((....)))))........(((.((((((.............(...,...((.....))....(((((....))))),-56.299999,-9.74,0.600732,(((((....)))))........(((.((((,"{'CCC': 3, 'CCG': 1, 'CGU': 2, 'GUU': 1, 'UUU'...","{'UAG': 1, 'AGC': 1, 'GCU': 1, 'CUG': 1, 'UGA'...",True,68.0,False,N/A,N/A,N/A,UAGCUGACCGAGGGACCCCCGUAAACGGGGCCCCGUUUACGGGGGU...,(((((((((((((((((((((((((((((())))))))))))))))...,-116.010002,0.530864,0.469136,0.500000,0.500000,0.666667,0.333333,0.026077,0.151723,0.068870,0.718246,0.783586,0.674069,"{'UAG': 3, 'AGC': 4, 'GCU': 3, 'CUG': 2, 'UGA'...",.......((..(((.((((((.......(((((.((......))((...,-341.070007,0.620253,0.379747,0.375672,0.692694,1.0
592953,1,1.0,25.0,Green Riboswitches,MS2 Virus,144 orthoganal first gen,180,1635,1635,3396,3396,ACCCCGUUUACGGGGGUCCCUCGGUCAGCUGGGAGUAAAUGAAUAA...,ACCCCGUUUACGGGGGUCCCUCGGUCAGCU,AGCUGACCGAGGGACCCCCGUAAACGGGGU,AGCUGACCGAGGGACCCCCGUAAACGGGGUACCCCGUUUACGGGGG...,ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGT...,.(((((....)))))........(((.((((((............(...,..((.....))....(((((....))))).,-54.270000,-10.55,0.631996,.(((((....)))))........(((.(((,"{'ACC': 3, 'CCC': 3, 'CCG': 1, 'CGU': 2, 'GUU'...","{'AGC': 1, 'GCU': 1, 'CUG': 1, 'UGA': 1, 'GAC'...",True,68.0,False,N/A,N/A,N/A,AGCUGACCGAGGGACCCCCGUAAACGGGGUACCCCGUUUACGGGGG...,(((((((((((((((((((((((((((((())))))))))))))))...,-116.309998,0.530864,0.469136,0.500000,0.500000,0.666667,0.333333,0.046032,0.175548,0.071386,0.716120,0.782657,0.673208,"{'AGC': 4, 'GCU': 3, 'CUG': 3, 'UGA': 3, 'GAC'...",.......((..(((.((((((.......(((((.((......))((...,-341.070007,0.620253,0.379747,0.375672,0.692694,1.0
592954,1,1.0,25.0,Green Riboswitches,MS2 Virus,144 orthoganal first gen,180,1636,1636,3397,3397,CACCCCGUUUACGGGGGUCCCUCGGUCAGCGGGAGUAAAUGAAUAA...,CACCCCGUUUACGGGGGUCCCUCGGUCAGC,GCUGACCGAGGGACCCCCGUAAACGGGGUG,GCUGACCGAGGGACCCCCGUAAACGGGGUGCACCCCGUUUACGGGG...,ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGT...,.((((((((..(((((...)))))...)))))).)).........(...,.((.....))....(((((....)))))..,-53.590000,-10.55,0.598615,.((((((((..(((((...)))))...))),"{'CAC': 2, 'ACC': 3, 'CCC': 3, 'CCG': 1, 'CGU'...","{'GCU': 1, 'CUG': 1, 'UGA': 1, 'GAC': 2, 'ACC'...",True,68.0,False,N/A,N/A,N/A,GCUGACCGAGGGACCCCCGUAAACGGGGUGCACCCCGUUUACGGGG...,(((((((((((((((((((((((((((((())))))))))))))))...,-118.620003,0.543210,0.456790,0.508197,0.491803,0.700000,0.300000,0.133451,0.257925,0.066686,0.720316,0.775283,0.672834,"{'GCU': 2, 'CUG': 2, 'UGA': 3, 'GAC': 4, 'ACC'...",.......((..(((.((((((.......(((((.((......))((...,-341.070007,0.620253,0.379747,0.375672,0.692694,1.0
592955,1,1.0,25.0,Green Riboswitches,MS2 Virus,144 orthoganal first gen,180,1637,1637,3398,3398,CCACCCCGUUUACGGGGGUCCCUCGGUCAGGGGAGUAAAUGAAUAA...,CCACCCCGUUUACGGGGGUCCCUCGGUCAG,CUGACCGAGGGACCCCCGUAAACGGGGUGG,CUGACCGAGGGACCCCCGUAAACGGGGUGGCCACCCCGUUUACGGG...,ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGT...,...(((((....)))))......(.((((((..............(...,............((((((....))))).).,-53.869999,-10.99,0.624758,...(((((....)))))......(.(((((,"{'CCA': 1, 'CAC': 2, 'ACC': 3, 'CCC': 3, 'CCG'...","{'CUG': 1, 'UGA': 1, 'GAC': 2, 'ACC': 2, 'CCG'...",True,68.0,False,N/A,N/A,N/A,CUGACCGAGGGACCCCCGUAAACGGGGUGGCCACCCCGUUUACGGG...,(((((((((((((((((((((((((((((())))))))))))))))...,-118.000000,0.543210,0.456790,0.508197,0.491803,0.700000,0.300000,0.098313,0.179838,0.063579,0.731871,0.764807,0.673467,"{'CUG': 2, 'UGA': 3, 'GAC': 4, 'ACC': 5, 'CCG'...",.......((..(((.((((((.......(((((.((......))((...,-341.070007,0.620253,0.379747,0.375672,0.692694,1.0

,label,salt_molarity,temperature (Celsius),name_of_riboswitch_data,name_of_target_data,riboswitch_subcategory,switch_row,target_row,trigger_row,target_location,trigger_location,riboswitch_sequence,target_sequence,trigger_sequence,target_trigger_complex,reporter_sequence,complex_nucelotides,switch_structure,target_structure,reporter_structure,complex_structure,trigger_target_binding_percentage,switch_energy,target_energy,reporter_energy,complex_energy,switch_gc,switch_at,target_gc,target_at,reporter_gc,reporter_at,complex_gc,complex_at,switch_ensemble_defect,target_ensemble_defect,reporter_ensemble_defect,complex_ensemble_defect,switch_single_strandedness,target_single_strandedness,reporter_single_strandedness,complex_single_strandedness,trigger_single_strandedness,trigger_structure,switch_kmers,target_kmers,complex_kmers,rbs_validity,rbs_location,valid_loop,loop_sequence,loop_structure,loop_energy
0,1,0.1,25.0,Green Riboswitches,MS2 Virus,forward engineered 4,0,0,0,1761,1761,AAGAGUUGAACUUCUUUGUUGUCUUCGACAGGGUCUUAUCUUAUCU...,UGUCGAAGACAACAAAGAAGUUCAACUCUU,AAGAGUUGAACUUCUUUGUUGUCUUCGACA,UGUCGAAGACAACAAAGAAGUUCAACUCUUAAGAGUUGAACUUCUU...,ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGT...,UGUCGAAGACAACAAAGAAGUUCAACUCUUAAGAGUUGAACUUCUU...,.(((...((....((((((((....)))))))).....))...)))...,((((...))))...................,.......((..(((.((((((.......(((((...........((...,(((((((((((((((((((((((((((((())))))))))))))))...,1.0,-39.180000,-2.22,-297.820007,-90.570000,0.418605,0.581395,0.366667,0.633333,0.620253,0.379747,0.414201,0.585799,0.121307,0.288612,0.339670,0.070971,0.715622,0.741619,0.697854,0.656634,0.567852,.(((...((....((((((((....))))),"{'AAG': 2, 'AGA': 6, 'GAG': 4, 'AGU': 1, 'GUU'...","{'UGU': 1, 'GUC': 1, 'UCG': 1, 'CGA': 1, 'GAA'...","{'UGU': 3, 'GUC': 3, 'UCG': 3, 'CGA': 3, 'GAA'...",True,75.0,True,ACAGAAACAGAGGAGAU,((............).),0.0
1,1,0.1,25.0,Green Riboswitches,MS2 Virus,forward engineered 4,0,1,1,1762,1762,AAAGAGUUGAACUUCUUUGUUGUCUUCGACGGGUCUUAUCUUAUCU...,GUCGAAGACAACAAAGAAGUUCAACUCUUU,AAAGAGUUGAACUUCUUUGUUGUCUUCGAC,GUCGAAGACAACAAAGAAGUUCAACUCUUUAAAGAGUUGAACUUCU...,ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGT...,GUCGAAGACAACAAAGAAGUUCAACUCUUUAAAGAGUUGAACUUCU...,((((((......))))))((((((...((.(((......))).))....,(((...)))...(((((.((...))))))),.......((..(((.((((((.......(((((...........((...,(((((((((((((((((((((((((((((())))))))))))))))...,1.0,-36.759998,-2.55,-297.820007,-90.870003,0.418605,0.581395,0.366667,0.633333,0.620253,0.379747,0.414201,0.585799,0.219631,0.169816,0.339670,0.069966,0.710996,0.721629,0.697854,0.655846,0.610438,((((((......))))))((((((...((.,"{'AAA': 6, 'AAG': 2, 'AGA': 6, 'GAG': 4, 'AGU'...","{'GUC': 1, 'UCG': 1, 'CGA': 1, 'GAA': 2, 'AAG'...","{'GUC': 3, 'UCG': 3, 'CGA': 3, 'GAA': 5, 'AAG'...",True,75.0,True,ACAGAAACAGAGGAGAU,((............).),0.0
2,1,0.1,25.0,Green Riboswitches,MS2 Virus,forward engineered 4,0,2,2,1763,1763,UAAAGAGUUGAACUUCUUUGUUGUCUUCGAGGGUCUUAUCUUAUCU...,UCGAAGACAACAAAGAAGUUCAACUCUUUA,UAAAGAGUUGAACUUCUUUGUUGUCUUCGA,UCGAAGACAACAAAGAAGUUCAACUCUUUAUAAAGAGUUGAACUUC...,ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGT...,UCGAAGACAACAAAGAAGUUCAACUCUUUAUAAAGAGUUGAACUUC...,.((((((......))))))((((((.....((((...............,...........(((((.((...))))))).,.......((..(((.((((((.......(((((...........((...,(((((((((((((((((((((((((((((())))))))))))))))...,1.0,-37.310001,-1.86,-297.820007,-88.260002,0.410853,0.589147,0.333333,0.666667,0.620253,0.379747,0.402367,0.597633,0.123665,0.208042,0.339670,0.069328,0.705704,0.793337,0.697854,0.656291,0.582332,.((((((......))))))((((((.....,"{'UAA': 3, 'AAA': 6, 'AAG': 2, 'AGA': 6, 'GAG'...","{'UCG': 1, 'CGA': 1, 'GAA': 2, 'AAG': 3, 'AGA'...","{'UCG': 3, 'CGA': 3, 'GAA': 5, 'AAG': 5, 'AGA'...",True,75.0,True,ACAGAAACAGAGGAGAU,((............).),0.0
3,1,0.1,25.0,Green Riboswitches,MS2 Virus,forward engineered 4,0,3,3,1764,1764,AUAAAGAGUUGAACUUCUUUGUUGUCUUCGGGGUCUUAUCUUAUCU...,CGAAGACAACAAAGAAGUUCAACUCUUUAU,AUAAAGAGUUGAACUUCUUUGUUGUCUUCG,CGAAGACAACAAAGAAGUUCAACUCUUUAUAUAAAGAGUUGAACUU...,ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGT...,CGAAGACAACAAAGAAGUUCAACUCUUUAUAUAAAGAGUUGAACUU...,((((((((......))))))))((((.(((((.................,..........(((((.((...)))))))..,.......((..(((.((((((.......(((((...........((...,(((((((((((((((((((((((((((((())))))))))))))))...,1.0,-39.869999,-1.86,-297.820007,-88.029999,0.410853,0.589147,0.333333,0.666667,0.620253,0.379747,0.402367,0.597633,0.077246,0.207414,0.339670,0.068155,0.696882,0.793421,0.697854,0.655946,0.518079,((((((((......))))))))((((.(((,"{'AUA': 4, 'UAA': 3, 'AAA': 6, 'AAG': 2, 'AGA'...","{'CGA': 1, 'GAA': 2, 'AAG': 3, 'AGA': 2, 'GAC'...","{'CGA': 2, 'GAA': 5, 'AAG': 5, 'AGA': 8, 'GAC'...",True,75.0,True,ACAGAAACAGAGGAGAU,((............).),0.0
4,1,0.1,25.0,Green Riboswitches,MS2 Virus,forward engineered 4,0,4,4,1765,1765,CAUAAAGAGUUGAACUUCUUUGUUGUCUUCGGGUCUUAUCUUAUCU...,GAAGACAACAAAGAAGUUCAACUCUUUAUG,CAUAAAGAGUUGAACUUCUUUGUUGUCUUC,GAAGACAACAAAGAAGUUCAACUCUUUAUGCAUAAAGAGUUGAACU...,ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGT...,GAAGACAACAAAGAAGUUCAACUCUUUAUGCAUAAAGAGUUGAACU...,.((((((((......))))))))((((.((((((...............,.........(((((.((...)))))))...,.......((..(((.((((((.......(((((...........((...,(((((((((((((((((((((((((((((())))))))))))))))...,1.0,-42.980000,-1.86,-297.820007,-88.830002,0.410853,0.589147,0.333333,0.666667,0.620253,0.379747,0.402367,0.597633,0.040454,0.195940,0.339670,0.064349,0.688818,0.792237,0.697854,0.655820,0.536631,.((((((((......))))))))((((.((,"{'CAU': 2, 'AUA': 4, 'UAA': 3, 'AAA': 6, 'AAG'...","{'GAA': 2, 'AAG': 3, 'AGA': 2, 'GAC': 1, 'ACA'...","{'GAA': 5, 'AAG': 5, 'AGA': 8, 'GAC': 1, 'ACA'...",True,75.0,True,ACAGAAACAGAGGAGAU,((............).),0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
592951,1,1.0,25.0,Green Riboswitches,MS2 Virus,144 orthoganal first gen,180,1633,1633,3394,3394,CCCGUUUACGGGGGUCCCUCGGUCAGCUACGGGAGUAAAUGAAUAA...,GUAGCUGACCGAGGGACCCCCGUAAACGGG,CCCGUUUACGGGGGUCCCUCGGUCAGCUAC,GUAGCUGACCGAGGGACCCCCGUAAACGGGCCCGUUUACGGGGGUC...,ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGT...,GUAGCUGACCGAGGGACCCCCGUAAACGGGCCCGUUUACGGGGGUC...,((((....)))).(((((..(((((..(((....)))..)))...(...,((..((.....))..)).((((....)))),.......((..(((.((((((.......(((((.((......))((...,(((((((((((((((((((((((((((((())))))))))))))))...,1.0,-51.580002,-7.98,-341.070007,-116.470001,0.500000,0.500000,0.666667,0.333333,0.620253,0.379747,0.530864,0.469136,0.062159,0.129106,0.375672,0.066760,0.697579,0.753355,0.692694,0.672812,0.449380,((((....)))).(((((..(((((..(((,"{'CCC': 2, 'CCG': 1, 'CGU': 2, 'GUU': 1, 'UUU'...","{'GUA': 2, 'UAG': 1, 'AGC': 1, 'GCU': 1, 'CUG'...","{'GUA': 5, 'UAG': 2, 'AGC': 4, 'GCU': 3, 'CUG'...",True,68.0,False,N/A,N/A,N/A
592952,1,1.0,25.0,Green Riboswitches,MS2 Virus,144 orthoganal first gen,180,1634,1634,3395,3395,CCCCGUUUACGGGGGUCCCUCGGUCAGCUAGGGAGUAAAUGAAUAA...,UAGCUGACCGAGGGACCCCCGUAAACGGGG,CCCCGUUUACGGGGGUCCCUCGGUCAGCUA,UAGCUGACCGAGGGACCCCCGUAAACGGGGCCCCGUUUACGGGGGU...,ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGT...,UAGCUGACCGAGGGACCCCCGUAAACGGGGCCCCGUUUACGGGGGU...,(((((....)))))........(((.((((((.............(...,...((.....))....(((((....))))),.......((..(((.((((((.......(((((.((......))((...,(((((((((((((((((((((((((((((())))))))))))))))...,1.0,-56.299999,-9.74,-341.070007,-116.010002,0.500000,0.500000,0.666667,0.333333,0.620253,0.379747,0.530864,0.469136,0.026077,0.151723,0.375672,0.068870,0.718246,0.783586,0.692694,0.674069,0.600732,(((((....)))))........(((.((((,"{'CCC': 3, 'CCG': 1, 'CGU': 2, 'GUU': 1, 'UUU'...","{'UAG': 1, 'AGC': 1, 'GCU': 1, 'CUG': 1, 'UGA'...","{'UAG': 3, 'AGC': 4, 'GCU': 3, 'CUG': 2, 'UGA'...",True,68.0,False,N/A,N/A,N/A
592953,1,1.0,25.0,Green Riboswitches,MS2 Virus,144 orthoganal first gen,180,1635,1635,3396,3396,ACCCCGUUUACGGGGGUCCCUCGGUCAGCUGGGAGUAAAUGAAUAA...,AGCUGACCGAGGGACCCCCGUAAACGGGGU,ACCCCGUUUACGGGGGUCCCUCGGUCAGCU,AGCUGACCGAGGGACCCCCGUAAACGGGGUACCCCGUUUACGGGGG...,ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGT...,AGCUGACCGAGGGACCCCCGUAAACGGGGUACCCCGUUUACGGGGG...,.(((((....)))))........(((.((((((............(...,..((.....))....(((((....))))).,.......((..(((.((((((.......(((((.((......))((...,(((((((((((((((((((((((((((((())))))))))))))))...,1.0,-54.270000,-10.55,-341.070007,-116.309998,0.500000,0.500000,0.666667,0.333333,0.620253,0.379747,0.530864,0.469136,0.046032,0.175548,0.375672,0.071386,0.716120,0.782657,0.692694,0.673208,0.631996,.(((((....)))))........(((.(((,"{'ACC': 3, 'CCC': 3, 'CCG': 1, 'CGU': 2, 'GUU'...","{'AGC': 1, 'GCU': 1, 'CUG': 1, 'UGA': 1, 'GAC'...","{'AGC': 4, 'GCU': 3, 'CUG': 3, 'UGA': 3, 'GAC'...",True,68.0,False,N/A,N/A,N/A
592954,1,1.0,25.0,Green Riboswitches,MS2 Virus,144 orthoganal first gen,180,1636,1636,3397,3397,CACCCCGUUUACGGGGGUCCCUCGGUCAGCGGGAGUAAAUGAAUAA...,GCUGACCGAGGGACCCCCGUAAACGGGGUG,CACCCCGUUUACGGGGGUCCCUCGGUCAGC,GCUGACCGAGGGACCCCCGUAAACGGGGUGCACCCCGUUUACGGGG...,ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGT...,GCUGACCGAGGGACCCCCGUAAACGGGGUGCACCCCGUUUACGGGG...,.((((((((..(((((...)))))...)))))).)).........(...,.((.....))....(((((....)))))..,.......((..(((.((((((.......(((((.((......))((...,(((((((((((((((((((((((((((((())))))))))))))))...,1.0,-53.590000,-10.55,-341.070007,-118.620003,0.508197,0.491803,0.700000,0.300000,0.620253,0.379747,0.543210,0.456790,0.133451,0.257925,0.375672,0.066686,0.720316,0.775283,0.692694,0.672834,0.598615,.((((((((..(((((...)))))...))),"{'CAC': 2, 'ACC': 3, 'CCC': 3, 'CCG': 1, 'CGU'...","{'GCU': 1, 'CUG': 1, 'UGA': 1, 'GAC': 2, 'ACC'...","{'GCU': 2, 'CUG': 2, 'UGA': 3, 'GAC': 4, 'ACC'...",True,68.0,False,N/A,N/A,N/A
592955,1,1.0,25.0,Green Riboswitches,MS2 Virus,144 orthoganal first gen,180,1637,1637,3398,3398,CCACCCCGUUUACGGGGGUCCCUCGGUCAGGGGAGUAAAUGAAUAA...,CUGACCGAGGGACCCCCGUAAACGGGGUGG,CCACCCCGUUUACGGGGGUCCCUCGGUCAG,CUGACCGAGGGACCCCCGUAAACGGGGUGGCCACCCCGUUUACGGG...,ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGT...,CUGACCGAGGGACCCCCGUAAACGGGGUGGCCACCCCGUUUACGGG...,...(((((....)))))......(.((((((..............(...,............((((((....))))).).,.......((..(((.((((((.......(((((.((......))((...,(((((((((((((((((((((((((((((())))))))))))))))...,1.0,-53.869999,-10.99,-341.070007,-118.000000,0.508197,0.491803,0.700000,0.300000,0.620253,0.379747,0.543210,0.456790,0.098313,0.179838,0.375672,0.063579,0.731871,0.764807,0.692694,0.673467,0.624758,...(((((....)))))......(.(((((,"{'CCA': 1, 'CAC': 2, 'ACC': 3, 'CCC': 3, 'CCG'...","{'CUG': 1, 'UGA': 1, 'GAC': 2, 'ACC': 2, 'CCG'...","{'CUG': 2, 'UGA': 3, 'GAC': 4, 'ACC': 5, 'CCG'...",True,68.0,False,N/A,N/A,N/A

In [ ]:
cherry_results = calculate_table(df, "Andrew's                      Riboswitches", 1, 30, ms2_data, "MS2 Virus", 0, ms2_cherry_csv_names, cherry_seq, cherry_preliminary_table, 1, 1, -1)
cherry_results.to_csv('large_cherry_MS2_data.csv')

In [ ]:
green_ms2_lacZ_results = calculate_table(green_sheet_dataframe, 'Green Riboswitches', 1, 30, ms2_data, 'MS2 Virus', 0, ms2_green_lacZ_csv_names, lacZ_seq, lacZ_preliminary_table, 1,1,0)

In [ ]:
green_lacZ_results = calculate_table(green_sheet_dataframe, 'Green Riboswitches', 1, 30, full_target_data, "Coxsackie Virus", 1,green_lacZ_csv_names, lacZ_seq, lacZ_preliminary_table, 1, 0 ,0)

In [ ]:
green_lacZ_results.to_csv('large_green_lacZ_data.csv')
green_lacZ_results.to_csv('large_green_lacZ_tab.csv', sep='\t')

In [ ]:
green_lacZ_results.to_csv('large_green_lacZ_data.csv')

In [ ]:
cherry_results = calculate_table(df, "Andrew's Riboswitches",1, 30, full_target_data, "Coxsackie Virus", 1, cherry_csv_names, cherry_seq, cherry_preliminary_table,1, 0, -1)

cherry_results.to_csv('large_cherry_data.csv')
cherry_results.to_csv('large_cherry_tab.csv', sep='\t')

In [ ]:
green_cherry_results = calculate_table(green_sheet_dataframe, 'Green Riboswitches',1, 30, full_target_data, "Coxsackie Virus", 1, green_cherry_csv_names, cherry_seq, cherry_preliminary_table,1, 0, 0)

In [ ]:
green_cherry_results.to_csv('large_green_cherry_data.csv')
green_cherry_results.to_csv('large_green_cherry_tab.csv', sep='\t')

In [ ]:
# testdf = pd.read_csv('(0.01) Green-Cherry-Cox-Data.csv')
# display(testdf)

In [ ]:
# testdf2 = testdf.sort_values(by=['trigger_target_binding_percentage'], ascending=False)
# display(testdf2)